//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActivityProxy
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AGS_Activity_Retrieve", Namespace="http://schemas.datacontract.org/2004/07/SmartServe.BusinessLogicLayer.BusinessEnt" +
        "ities")]
    public partial class AGS_Activity_Retrieve : object
    {
        
        private string ActivityIDField;
        
        private string ChannelField;
        
        private string ContactNameField;
        
        private string CreatedByField;
        
        private System.Nullable<System.DateTime> CreatedOnField;
        
        private string CustomerIDField;
        
        private string CustomerNameField;
        
        private string DesignationField;
        
        private string DocumentIDField;
        
        private string EmailIDField;
        
        private System.Nullable<System.DateTime> FromDateField;
        
        private string ListofDisussionField;
        
        private string MobileNumberField;
        
        private string ModifiedByField;
        
        private System.Nullable<System.DateTime> ModifiedOnField;
        
        private System.Nullable<System.DateTime> NextPlannedVisitField;
        
        private string ObjectiveoftheVisitField;
        
        private string OtherTeamMembersField;
        
        private string OutcomeoftheMeetingField;
        
        private string RemarksField;
        
        private string StatusField;
        
        private string SupportRequiredField;
        
        private string TempActivityIDField;
        
        private System.Nullable<System.DateTime> ToDateField;
        
        private string TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActivityID
        {
            get
            {
                return this.ActivityIDField;
            }
            set
            {
                this.ActivityIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Channel
        {
            get
            {
                return this.ChannelField;
            }
            set
            {
                this.ChannelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactName
        {
            get
            {
                return this.ContactNameField;
            }
            set
            {
                this.ContactNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this.CreatedByField;
            }
            set
            {
                this.CreatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedOn
        {
            get
            {
                return this.CreatedOnField;
            }
            set
            {
                this.CreatedOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerID
        {
            get
            {
                return this.CustomerIDField;
            }
            set
            {
                this.CustomerIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName
        {
            get
            {
                return this.CustomerNameField;
            }
            set
            {
                this.CustomerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Designation
        {
            get
            {
                return this.DesignationField;
            }
            set
            {
                this.DesignationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentID
        {
            get
            {
                return this.DocumentIDField;
            }
            set
            {
                this.DocumentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailID
        {
            get
            {
                return this.EmailIDField;
            }
            set
            {
                this.EmailIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FromDate
        {
            get
            {
                return this.FromDateField;
            }
            set
            {
                this.FromDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ListofDisussion
        {
            get
            {
                return this.ListofDisussionField;
            }
            set
            {
                this.ListofDisussionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileNumber
        {
            get
            {
                return this.MobileNumberField;
            }
            set
            {
                this.MobileNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy
        {
            get
            {
                return this.ModifiedByField;
            }
            set
            {
                this.ModifiedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ModifiedOn
        {
            get
            {
                return this.ModifiedOnField;
            }
            set
            {
                this.ModifiedOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> NextPlannedVisit
        {
            get
            {
                return this.NextPlannedVisitField;
            }
            set
            {
                this.NextPlannedVisitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObjectiveoftheVisit
        {
            get
            {
                return this.ObjectiveoftheVisitField;
            }
            set
            {
                this.ObjectiveoftheVisitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OtherTeamMembers
        {
            get
            {
                return this.OtherTeamMembersField;
            }
            set
            {
                this.OtherTeamMembersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OutcomeoftheMeeting
        {
            get
            {
                return this.OutcomeoftheMeetingField;
            }
            set
            {
                this.OutcomeoftheMeetingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remarks
        {
            get
            {
                return this.RemarksField;
            }
            set
            {
                this.RemarksField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupportRequired
        {
            get
            {
                return this.SupportRequiredField;
            }
            set
            {
                this.SupportRequiredField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TempActivityID
        {
            get
            {
                return this.TempActivityIDField;
            }
            set
            {
                this.TempActivityIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ToDate
        {
            get
            {
                return this.ToDateField;
            }
            set
            {
                this.ToDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AGS_Activity_New", Namespace="http://schemas.datacontract.org/2004/07/SmartServe.BusinessLogicLayer.BusinessEnt" +
        "ities")]
    public partial class AGS_Activity_New : object
    {
        
        private string ChannelField;
        
        private string ContactNameField;
        
        private string CustomerIDField;
        
        private string CustomerNameField;
        
        private string DesignationField;
        
        private string DocumentIDField;
        
        private string EmailIDField;
        
        private System.Nullable<System.DateTime> FromDateField;
        
        private string ListofDisussionField;
        
        private string MobileNumberField;
        
        private System.Nullable<System.DateTime> NextPlannedVisitField;
        
        private string ObjectiveoftheVisitField;
        
        private string OtherTeamMembersField;
        
        private string RemarksField;
        
        private string SupportRequiredField;
        
        private System.Nullable<System.DateTime> ToDateField;
        
        private string TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Channel
        {
            get
            {
                return this.ChannelField;
            }
            set
            {
                this.ChannelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactName
        {
            get
            {
                return this.ContactNameField;
            }
            set
            {
                this.ContactNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerID
        {
            get
            {
                return this.CustomerIDField;
            }
            set
            {
                this.CustomerIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName
        {
            get
            {
                return this.CustomerNameField;
            }
            set
            {
                this.CustomerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Designation
        {
            get
            {
                return this.DesignationField;
            }
            set
            {
                this.DesignationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentID
        {
            get
            {
                return this.DocumentIDField;
            }
            set
            {
                this.DocumentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailID
        {
            get
            {
                return this.EmailIDField;
            }
            set
            {
                this.EmailIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FromDate
        {
            get
            {
                return this.FromDateField;
            }
            set
            {
                this.FromDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ListofDisussion
        {
            get
            {
                return this.ListofDisussionField;
            }
            set
            {
                this.ListofDisussionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileNumber
        {
            get
            {
                return this.MobileNumberField;
            }
            set
            {
                this.MobileNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> NextPlannedVisit
        {
            get
            {
                return this.NextPlannedVisitField;
            }
            set
            {
                this.NextPlannedVisitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObjectiveoftheVisit
        {
            get
            {
                return this.ObjectiveoftheVisitField;
            }
            set
            {
                this.ObjectiveoftheVisitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OtherTeamMembers
        {
            get
            {
                return this.OtherTeamMembersField;
            }
            set
            {
                this.OtherTeamMembersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remarks
        {
            get
            {
                return this.RemarksField;
            }
            set
            {
                this.RemarksField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupportRequired
        {
            get
            {
                return this.SupportRequiredField;
            }
            set
            {
                this.SupportRequiredField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ToDate
        {
            get
            {
                return this.ToDateField;
            }
            set
            {
                this.ToDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AGS_Activity_Modify", Namespace="http://schemas.datacontract.org/2004/07/SmartServe.BusinessLogicLayer.BusinessEnt" +
        "ities")]
    public partial class AGS_Activity_Modify : object
    {
        
        private string ActivityIDField;
        
        private string ChannelField;
        
        private string ContactNameField;
        
        private string CustomerIDField;
        
        private string CustomerNameField;
        
        private string DesignationField;
        
        private string DocumentIDField;
        
        private string EmailIDField;
        
        private System.Nullable<System.DateTime> FromDateField;
        
        private string ListofDisussionField;
        
        private string MobileNumberField;
        
        private string ModifiedByField;
        
        private System.Nullable<System.DateTime> ModifiedOnField;
        
        private System.Nullable<System.DateTime> NextPlannedVisitField;
        
        private string ObjectiveoftheVisitField;
        
        private string OtherTeamMembersField;
        
        private string OutcomeoftheMeetingField;
        
        private string RemarksField;
        
        private string SupportRequiredField;
        
        private System.Nullable<System.DateTime> ToDateField;
        
        private string TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActivityID
        {
            get
            {
                return this.ActivityIDField;
            }
            set
            {
                this.ActivityIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Channel
        {
            get
            {
                return this.ChannelField;
            }
            set
            {
                this.ChannelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactName
        {
            get
            {
                return this.ContactNameField;
            }
            set
            {
                this.ContactNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerID
        {
            get
            {
                return this.CustomerIDField;
            }
            set
            {
                this.CustomerIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName
        {
            get
            {
                return this.CustomerNameField;
            }
            set
            {
                this.CustomerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Designation
        {
            get
            {
                return this.DesignationField;
            }
            set
            {
                this.DesignationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentID
        {
            get
            {
                return this.DocumentIDField;
            }
            set
            {
                this.DocumentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailID
        {
            get
            {
                return this.EmailIDField;
            }
            set
            {
                this.EmailIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FromDate
        {
            get
            {
                return this.FromDateField;
            }
            set
            {
                this.FromDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ListofDisussion
        {
            get
            {
                return this.ListofDisussionField;
            }
            set
            {
                this.ListofDisussionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileNumber
        {
            get
            {
                return this.MobileNumberField;
            }
            set
            {
                this.MobileNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy
        {
            get
            {
                return this.ModifiedByField;
            }
            set
            {
                this.ModifiedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ModifiedOn
        {
            get
            {
                return this.ModifiedOnField;
            }
            set
            {
                this.ModifiedOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> NextPlannedVisit
        {
            get
            {
                return this.NextPlannedVisitField;
            }
            set
            {
                this.NextPlannedVisitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObjectiveoftheVisit
        {
            get
            {
                return this.ObjectiveoftheVisitField;
            }
            set
            {
                this.ObjectiveoftheVisitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OtherTeamMembers
        {
            get
            {
                return this.OtherTeamMembersField;
            }
            set
            {
                this.OtherTeamMembersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OutcomeoftheMeeting
        {
            get
            {
                return this.OutcomeoftheMeetingField;
            }
            set
            {
                this.OutcomeoftheMeetingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remarks
        {
            get
            {
                return this.RemarksField;
            }
            set
            {
                this.RemarksField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupportRequired
        {
            get
            {
                return this.SupportRequiredField;
            }
            set
            {
                this.SupportRequiredField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ToDate
        {
            get
            {
                return this.ToDateField;
            }
            set
            {
                this.ToDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AGS_Activity_ReSchedule", Namespace="http://schemas.datacontract.org/2004/07/SmartServe.BusinessLogicLayer.BusinessEnt" +
        "ities")]
    public partial class AGS_Activity_ReSchedule : object
    {
        
        private string ActivityIDField;
        
        private System.Nullable<System.DateTime> FromDateField;
        
        private string RemarksField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActivityID
        {
            get
            {
                return this.ActivityIDField;
            }
            set
            {
                this.ActivityIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FromDate
        {
            get
            {
                return this.FromDateField;
            }
            set
            {
                this.FromDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remarks
        {
            get
            {
                return this.RemarksField;
            }
            set
            {
                this.RemarksField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AGS_Activity_Close", Namespace="http://schemas.datacontract.org/2004/07/SmartServe.BusinessLogicLayer.BusinessEnt" +
        "ities")]
    public partial class AGS_Activity_Close : object
    {
        
        private string ActivityIDField;
        
        private string LatitudeField;
        
        private string LocationField;
        
        private string LongitudeField;
        
        private string OutcomeoftheMeetingField;
        
        private string RemarksField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActivityID
        {
            get
            {
                return this.ActivityIDField;
            }
            set
            {
                this.ActivityIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Latitude
        {
            get
            {
                return this.LatitudeField;
            }
            set
            {
                this.LatitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location
        {
            get
            {
                return this.LocationField;
            }
            set
            {
                this.LocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Longitude
        {
            get
            {
                return this.LongitudeField;
            }
            set
            {
                this.LongitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OutcomeoftheMeeting
        {
            get
            {
                return this.OutcomeoftheMeetingField;
            }
            set
            {
                this.OutcomeoftheMeetingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remarks
        {
            get
            {
                return this.RemarksField;
            }
            set
            {
                this.RemarksField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ActivityProxy.IActivityProxyService")]
    public interface IActivityProxyService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActivityProxyService/RetrieveAll", ReplyAction="http://tempuri.org/IActivityProxyService/RetrieveAllResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ActivityProxy.AGS_Activity_Retrieve>> RetrieveAllAsync(string sortBy, string sortOrder, int pageSize, string marker, int currentIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActivityProxyService/Retrieve", ReplyAction="http://tempuri.org/IActivityProxyService/RetrieveResponse")]
        System.Threading.Tasks.Task<ActivityProxy.AGS_Activity_Retrieve> RetrieveAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActivityProxyService/Count", ReplyAction="http://tempuri.org/IActivityProxyService/CountResponse")]
        System.Threading.Tasks.Task<int> CountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActivityProxyService/Search", ReplyAction="http://tempuri.org/IActivityProxyService/SearchResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ActivityProxy.AGS_Activity_Retrieve>> SearchAsync(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActivityProxyService/RetrieveByDocumentId", ReplyAction="http://tempuri.org/IActivityProxyService/RetrieveByDocumentIdResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ActivityProxy.AGS_Activity_Retrieve>> RetrieveByDocumentIdAsync(string documentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActivityProxyService/RetrieveByDate", ReplyAction="http://tempuri.org/IActivityProxyService/RetrieveByDateResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ActivityProxy.AGS_Activity_Retrieve>> RetrieveByDateAsync(string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActivityProxyService/Create", ReplyAction="http://tempuri.org/IActivityProxyService/CreateResponse")]
        System.Threading.Tasks.Task<string> CreateAsync(ActivityProxy.AGS_Activity_New model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActivityProxyService/Update", ReplyAction="http://tempuri.org/IActivityProxyService/UpdateResponse")]
        System.Threading.Tasks.Task<bool> UpdateAsync(string id, ActivityProxy.AGS_Activity_Modify model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActivityProxyService/Delete", ReplyAction="http://tempuri.org/IActivityProxyService/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActivityProxyService/ReSchedule", ReplyAction="http://tempuri.org/IActivityProxyService/ReScheduleResponse")]
        System.Threading.Tasks.Task<bool> ReScheduleAsync(string id, ActivityProxy.AGS_Activity_ReSchedule model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActivityProxyService/Close", ReplyAction="http://tempuri.org/IActivityProxyService/CloseResponse")]
        System.Threading.Tasks.Task<bool> CloseAsync(string id, ActivityProxy.AGS_Activity_Close model);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    public interface IActivityProxyServiceChannel : ActivityProxy.IActivityProxyService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    public partial class ActivityProxyServiceClient : System.ServiceModel.ClientBase<ActivityProxy.IActivityProxyService>, ActivityProxy.IActivityProxyService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ActivityProxyServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ActivityProxyServiceClient.GetBindingForEndpoint(endpointConfiguration), ActivityProxyServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ActivityProxyServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ActivityProxyServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ActivityProxyServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ActivityProxyServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ActivityProxyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ActivityProxy.AGS_Activity_Retrieve>> RetrieveAllAsync(string sortBy, string sortOrder, int pageSize, string marker, int currentIndex)
        {
            return base.Channel.RetrieveAllAsync(sortBy, sortOrder, pageSize, marker, currentIndex);
        }
        
        public System.Threading.Tasks.Task<ActivityProxy.AGS_Activity_Retrieve> RetrieveAsync(string id)
        {
            return base.Channel.RetrieveAsync(id);
        }
        
        public System.Threading.Tasks.Task<int> CountAsync()
        {
            return base.Channel.CountAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ActivityProxy.AGS_Activity_Retrieve>> SearchAsync(string key)
        {
            return base.Channel.SearchAsync(key);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ActivityProxy.AGS_Activity_Retrieve>> RetrieveByDocumentIdAsync(string documentId)
        {
            return base.Channel.RetrieveByDocumentIdAsync(documentId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ActivityProxy.AGS_Activity_Retrieve>> RetrieveByDateAsync(string date)
        {
            return base.Channel.RetrieveByDateAsync(date);
        }
        
        public System.Threading.Tasks.Task<string> CreateAsync(ActivityProxy.AGS_Activity_New model)
        {
            return base.Channel.CreateAsync(model);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAsync(string id, ActivityProxy.AGS_Activity_Modify model)
        {
            return base.Channel.UpdateAsync(id, model);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(string id)
        {
            return base.Channel.DeleteAsync(id);
        }
        
        public System.Threading.Tasks.Task<bool> ReScheduleAsync(string id, ActivityProxy.AGS_Activity_ReSchedule model)
        {
            return base.Channel.ReScheduleAsync(id, model);
        }
        
        public System.Threading.Tasks.Task<bool> CloseAsync(string id, ActivityProxy.AGS_Activity_Close model)
        {
            return base.Channel.CloseAsync(id, model);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync1()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ActivityProxySOAPEndPoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ActivityProxySOAPHttpsEndPoint))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ActivityProxySOAPEndPoint))
            {
                return new System.ServiceModel.EndpointAddress("http://ps-win-cscrmqty.voltasworld.com/GateKeeper/Proxy/ActivityProxyService.svc/" +
                        "SOAP");
            }
            if ((endpointConfiguration == EndpointConfiguration.ActivityProxySOAPHttpsEndPoint))
            {
                return new System.ServiceModel.EndpointAddress("https://vserveq.voltasworld.com/GateKeeper/Proxy/ActivityProxyService.svc/SOAP");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ActivityProxySOAPEndPoint,
            
            ActivityProxySOAPHttpsEndPoint,
        }
    }
}
