//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderProxy
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AGS_Order", Namespace="http://schemas.datacontract.org/2004/07/SmartServe.BusinessLogicLayer.BusinessEnt" +
        "ities")]
    public partial class AGS_Order : object
    {
        
        private string AccountIDField;
        
        private string AccountNameField;
        
        private string Address1Field;
        
        private string ArchitectField;
        
        private System.Nullable<double> BasicSaleValueField;
        
        private string BranchField;
        
        private string BranchNameField;
        
        private string BusinessSegmentField;
        
        private string BusinessSegmentIDField;
        
        private string CRMLeadIDField;
        
        private string CRMOPPORTUNITYIDField;
        
        private string CRMOrderIDField;
        
        private string CRMQUOTATIONIDField;
        
        private string ChannelField;
        
        private string CityField;
        
        private string Classification1Field;
        
        private string Classification2Field;
        
        private string Classification3Field;
        
        private string Classification3IDField;
        
        private string Classification4Field;
        
        private string CompetitorNameField;
        
        private string CompetitorName2Field;
        
        private System.Nullable<double> CompetitorPriceField;
        
        private string ConsultantField;
        
        private string ContactNameField;
        
        private System.Nullable<double> ContractValueField;
        
        private string CreatedByField;
        
        private System.Nullable<System.DateTime> CreatedOnField;
        
        private string CurrencyField;
        
        private System.Nullable<double> CurrencyValueField;
        
        private string CustomerClassificationField;
        
        private string CustomerClassificationIdField;
        
        private string CustomerSegmentField;
        
        private string CustomerSegmentIDField;
        
        private string CustomerTypeField;
        
        private string CustomerTypeIDField;
        
        private string DescriptionField;
        
        private string DivisionField;
        
        private string DivisionNameField;
        
        private System.Nullable<System.DateTime> DocumentCreatedDateField;
        
        private System.Nullable<System.DateTime> EnquiryDateField;
        
        private System.Nullable<double> GrossMarginField;
        
        private System.Nullable<System.DateTime> LikelyDeliveryDateField;
        
        private string MobileNumberField;
        
        private string ModifiedByField;
        
        private System.Nullable<System.DateTime> ModifiedOnField;
        
        private string ObjectTypeField;
        
        private string OderIdField;
        
        private System.Collections.Generic.List<OrderProxy.AGS_OrderProduct> OrderProductsField;
        
        private string OrderReasonsField;
        
        private System.Nullable<System.DateTime> OrderReferenceDateField;
        
        private string OrderReferenceIDField;
        
        private string OrderTypeField;
        
        private string PincodeField;
        
        private string PlantIDField;
        
        private string PlantNameField;
        
        private System.Nullable<System.DateTime> PoDateField;
        
        private string PoNoField;
        
        private string PriorityField;
        
        private string ProductRequiredField;
        
        private string ProjectNameField;
        
        private System.Nullable<System.DateTime> QuotationDateField;
        
        private string ReasonField;
        
        private string RegionField;
        
        private string RegionNameField;
        
        private string SAPOrderIDField;
        
        private string SalesOfficeField;
        
        private string StateField;
        
        private string StatusField;
        
        private string SubSegmentField;
        
        private string SubSegmentIDField;
        
        private string TempOrderIDField;
        
        private System.Nullable<double> TonnageField;
        
        private System.Nullable<double> TotalCostField;
        
        private System.Nullable<double> TotalValueField;
        
        private System.Nullable<double> TurnOverValueField;
        
        private string UserIDField;
        
        private string UsernameField;
        
        private string WonloseField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountID
        {
            get
            {
                return this.AccountIDField;
            }
            set
            {
                this.AccountIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountName
        {
            get
            {
                return this.AccountNameField;
            }
            set
            {
                this.AccountNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address1
        {
            get
            {
                return this.Address1Field;
            }
            set
            {
                this.Address1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Architect
        {
            get
            {
                return this.ArchitectField;
            }
            set
            {
                this.ArchitectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> BasicSaleValue
        {
            get
            {
                return this.BasicSaleValueField;
            }
            set
            {
                this.BasicSaleValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Branch
        {
            get
            {
                return this.BranchField;
            }
            set
            {
                this.BranchField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BranchName
        {
            get
            {
                return this.BranchNameField;
            }
            set
            {
                this.BranchNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BusinessSegment
        {
            get
            {
                return this.BusinessSegmentField;
            }
            set
            {
                this.BusinessSegmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BusinessSegmentID
        {
            get
            {
                return this.BusinessSegmentIDField;
            }
            set
            {
                this.BusinessSegmentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CRMLeadID
        {
            get
            {
                return this.CRMLeadIDField;
            }
            set
            {
                this.CRMLeadIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CRMOPPORTUNITYID
        {
            get
            {
                return this.CRMOPPORTUNITYIDField;
            }
            set
            {
                this.CRMOPPORTUNITYIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CRMOrderID
        {
            get
            {
                return this.CRMOrderIDField;
            }
            set
            {
                this.CRMOrderIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CRMQUOTATIONID
        {
            get
            {
                return this.CRMQUOTATIONIDField;
            }
            set
            {
                this.CRMQUOTATIONIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Channel
        {
            get
            {
                return this.ChannelField;
            }
            set
            {
                this.ChannelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Classification1
        {
            get
            {
                return this.Classification1Field;
            }
            set
            {
                this.Classification1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Classification2
        {
            get
            {
                return this.Classification2Field;
            }
            set
            {
                this.Classification2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Classification3
        {
            get
            {
                return this.Classification3Field;
            }
            set
            {
                this.Classification3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Classification3ID
        {
            get
            {
                return this.Classification3IDField;
            }
            set
            {
                this.Classification3IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Classification4
        {
            get
            {
                return this.Classification4Field;
            }
            set
            {
                this.Classification4Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompetitorName
        {
            get
            {
                return this.CompetitorNameField;
            }
            set
            {
                this.CompetitorNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompetitorName2
        {
            get
            {
                return this.CompetitorName2Field;
            }
            set
            {
                this.CompetitorName2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> CompetitorPrice
        {
            get
            {
                return this.CompetitorPriceField;
            }
            set
            {
                this.CompetitorPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Consultant
        {
            get
            {
                return this.ConsultantField;
            }
            set
            {
                this.ConsultantField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactName
        {
            get
            {
                return this.ContactNameField;
            }
            set
            {
                this.ContactNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> ContractValue
        {
            get
            {
                return this.ContractValueField;
            }
            set
            {
                this.ContractValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this.CreatedByField;
            }
            set
            {
                this.CreatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedOn
        {
            get
            {
                return this.CreatedOnField;
            }
            set
            {
                this.CreatedOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency
        {
            get
            {
                return this.CurrencyField;
            }
            set
            {
                this.CurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> CurrencyValue
        {
            get
            {
                return this.CurrencyValueField;
            }
            set
            {
                this.CurrencyValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerClassification
        {
            get
            {
                return this.CustomerClassificationField;
            }
            set
            {
                this.CustomerClassificationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerClassificationId
        {
            get
            {
                return this.CustomerClassificationIdField;
            }
            set
            {
                this.CustomerClassificationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerSegment
        {
            get
            {
                return this.CustomerSegmentField;
            }
            set
            {
                this.CustomerSegmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerSegmentID
        {
            get
            {
                return this.CustomerSegmentIDField;
            }
            set
            {
                this.CustomerSegmentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerType
        {
            get
            {
                return this.CustomerTypeField;
            }
            set
            {
                this.CustomerTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerTypeID
        {
            get
            {
                return this.CustomerTypeIDField;
            }
            set
            {
                this.CustomerTypeIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Division
        {
            get
            {
                return this.DivisionField;
            }
            set
            {
                this.DivisionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DivisionName
        {
            get
            {
                return this.DivisionNameField;
            }
            set
            {
                this.DivisionNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DocumentCreatedDate
        {
            get
            {
                return this.DocumentCreatedDateField;
            }
            set
            {
                this.DocumentCreatedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EnquiryDate
        {
            get
            {
                return this.EnquiryDateField;
            }
            set
            {
                this.EnquiryDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> GrossMargin
        {
            get
            {
                return this.GrossMarginField;
            }
            set
            {
                this.GrossMarginField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LikelyDeliveryDate
        {
            get
            {
                return this.LikelyDeliveryDateField;
            }
            set
            {
                this.LikelyDeliveryDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileNumber
        {
            get
            {
                return this.MobileNumberField;
            }
            set
            {
                this.MobileNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy
        {
            get
            {
                return this.ModifiedByField;
            }
            set
            {
                this.ModifiedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ModifiedOn
        {
            get
            {
                return this.ModifiedOnField;
            }
            set
            {
                this.ModifiedOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObjectType
        {
            get
            {
                return this.ObjectTypeField;
            }
            set
            {
                this.ObjectTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OderId
        {
            get
            {
                return this.OderIdField;
            }
            set
            {
                this.OderIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<OrderProxy.AGS_OrderProduct> OrderProducts
        {
            get
            {
                return this.OrderProductsField;
            }
            set
            {
                this.OrderProductsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderReasons
        {
            get
            {
                return this.OrderReasonsField;
            }
            set
            {
                this.OrderReasonsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> OrderReferenceDate
        {
            get
            {
                return this.OrderReferenceDateField;
            }
            set
            {
                this.OrderReferenceDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderReferenceID
        {
            get
            {
                return this.OrderReferenceIDField;
            }
            set
            {
                this.OrderReferenceIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderType
        {
            get
            {
                return this.OrderTypeField;
            }
            set
            {
                this.OrderTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pincode
        {
            get
            {
                return this.PincodeField;
            }
            set
            {
                this.PincodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlantID
        {
            get
            {
                return this.PlantIDField;
            }
            set
            {
                this.PlantIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlantName
        {
            get
            {
                return this.PlantNameField;
            }
            set
            {
                this.PlantNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PoDate
        {
            get
            {
                return this.PoDateField;
            }
            set
            {
                this.PoDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PoNo
        {
            get
            {
                return this.PoNoField;
            }
            set
            {
                this.PoNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Priority
        {
            get
            {
                return this.PriorityField;
            }
            set
            {
                this.PriorityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductRequired
        {
            get
            {
                return this.ProductRequiredField;
            }
            set
            {
                this.ProductRequiredField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProjectName
        {
            get
            {
                return this.ProjectNameField;
            }
            set
            {
                this.ProjectNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> QuotationDate
        {
            get
            {
                return this.QuotationDateField;
            }
            set
            {
                this.QuotationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason
        {
            get
            {
                return this.ReasonField;
            }
            set
            {
                this.ReasonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Region
        {
            get
            {
                return this.RegionField;
            }
            set
            {
                this.RegionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegionName
        {
            get
            {
                return this.RegionNameField;
            }
            set
            {
                this.RegionNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SAPOrderID
        {
            get
            {
                return this.SAPOrderIDField;
            }
            set
            {
                this.SAPOrderIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SalesOffice
        {
            get
            {
                return this.SalesOfficeField;
            }
            set
            {
                this.SalesOfficeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubSegment
        {
            get
            {
                return this.SubSegmentField;
            }
            set
            {
                this.SubSegmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubSegmentID
        {
            get
            {
                return this.SubSegmentIDField;
            }
            set
            {
                this.SubSegmentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TempOrderID
        {
            get
            {
                return this.TempOrderIDField;
            }
            set
            {
                this.TempOrderIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Tonnage
        {
            get
            {
                return this.TonnageField;
            }
            set
            {
                this.TonnageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> TotalCost
        {
            get
            {
                return this.TotalCostField;
            }
            set
            {
                this.TotalCostField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> TotalValue
        {
            get
            {
                return this.TotalValueField;
            }
            set
            {
                this.TotalValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> TurnOverValue
        {
            get
            {
                return this.TurnOverValueField;
            }
            set
            {
                this.TurnOverValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Wonlose
        {
            get
            {
                return this.WonloseField;
            }
            set
            {
                this.WonloseField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AGS_OrderProduct", Namespace="http://schemas.datacontract.org/2004/07/SmartServe.BusinessLogicLayer.BusinessEnt" +
        "ities")]
    public partial class AGS_OrderProduct : object
    {
        
        private System.Nullable<double> ContractValueField;
        
        private string CreatedByField;
        
        private System.Nullable<System.DateTime> CreatedOnField;
        
        private string CrmOrderIDField;
        
        private OrderProxy.EntityState EntityStateField;
        
        private System.Nullable<double> GrossMarginField;
        
        private System.Nullable<int> ItemNoField;
        
        private string MaterialGroupField;
        
        private string ModifiedByField;
        
        private System.Nullable<System.DateTime> ModifiedOnField;
        
        private OrderProxy.AGS_Order OrderField;
        
        private string ProductIDField;
        
        private string ProductNameField;
        
        private System.Nullable<int> QuantityField;
        
        private string TempOrderIDField;
        
        private System.Nullable<double> TotalTonnageQuantityField;
        
        private System.Nullable<double> TotalTonnageValueField;
        
        private System.Nullable<double> TotalValueField;
        
        private System.Nullable<double> TurnoverValueField;
        
        private System.Nullable<double> ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> ContractValue
        {
            get
            {
                return this.ContractValueField;
            }
            set
            {
                this.ContractValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this.CreatedByField;
            }
            set
            {
                this.CreatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedOn
        {
            get
            {
                return this.CreatedOnField;
            }
            set
            {
                this.CreatedOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CrmOrderID
        {
            get
            {
                return this.CrmOrderIDField;
            }
            set
            {
                this.CrmOrderIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OrderProxy.EntityState EntityState
        {
            get
            {
                return this.EntityStateField;
            }
            set
            {
                this.EntityStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> GrossMargin
        {
            get
            {
                return this.GrossMarginField;
            }
            set
            {
                this.GrossMarginField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ItemNo
        {
            get
            {
                return this.ItemNoField;
            }
            set
            {
                this.ItemNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaterialGroup
        {
            get
            {
                return this.MaterialGroupField;
            }
            set
            {
                this.MaterialGroupField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy
        {
            get
            {
                return this.ModifiedByField;
            }
            set
            {
                this.ModifiedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ModifiedOn
        {
            get
            {
                return this.ModifiedOnField;
            }
            set
            {
                this.ModifiedOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OrderProxy.AGS_Order Order
        {
            get
            {
                return this.OrderField;
            }
            set
            {
                this.OrderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductID
        {
            get
            {
                return this.ProductIDField;
            }
            set
            {
                this.ProductIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName
        {
            get
            {
                return this.ProductNameField;
            }
            set
            {
                this.ProductNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Quantity
        {
            get
            {
                return this.QuantityField;
            }
            set
            {
                this.QuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TempOrderID
        {
            get
            {
                return this.TempOrderIDField;
            }
            set
            {
                this.TempOrderIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> TotalTonnageQuantity
        {
            get
            {
                return this.TotalTonnageQuantityField;
            }
            set
            {
                this.TotalTonnageQuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> TotalTonnageValue
        {
            get
            {
                return this.TotalTonnageValueField;
            }
            set
            {
                this.TotalTonnageValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> TotalValue
        {
            get
            {
                return this.TotalValueField;
            }
            set
            {
                this.TotalValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> TurnoverValue
        {
            get
            {
                return this.TurnoverValueField;
            }
            set
            {
                this.TurnoverValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityState", Namespace="http://schemas.datacontract.org/2004/07/SmartServe.BusinessLogicLayer")]
    public enum EntityState : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unchanged = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Added = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Modified = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deleted = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AGS_UploadOrder", Namespace="http://schemas.datacontract.org/2004/07/SmartServe.BusinessLogicLayer.BusinessEnt" +
        "ities")]
    public partial class AGS_UploadOrder : object
    {
        
        private string AccountIDField;
        
        private string AccountNameField;
        
        private string Address1Field;
        
        private string ArchitectField;
        
        private System.Nullable<double> BasicSaleValueField;
        
        private string BranchField;
        
        private string BranchNameField;
        
        private string BusinessSegmentField;
        
        private string BusinessSegmentIDField;
        
        private string CRMLeadIDField;
        
        private string CRMOPPORTUNITYIDField;
        
        private string CRMOrderIDField;
        
        private string CRMQUOTATIONIDField;
        
        private string ChannelField;
        
        private string CityField;
        
        private string Classification1Field;
        
        private string Classification2Field;
        
        private string Classification3Field;
        
        private string Classification3IDField;
        
        private string Classification4Field;
        
        private string CompetitorNameField;
        
        private System.Nullable<double> CompetitorPriceField;
        
        private string ConsultantField;
        
        private string ContactNameField;
        
        private System.Nullable<double> ContractValueField;
        
        private string CurrencyField;
        
        private System.Nullable<double> CurrencyValueField;
        
        private string CustomerClassificationField;
        
        private string CustomerClassificationIdField;
        
        private string CustomerSegmentField;
        
        private string CustomerSegmentIDField;
        
        private string CustomerTypeField;
        
        private string CustomerTypeIDField;
        
        private string DescriptionField;
        
        private string DivisionField;
        
        private string DivisionNameField;
        
        private System.Nullable<System.DateTime> DocumentCreatedDateField;
        
        private System.Nullable<System.DateTime> EnquiryDateField;
        
        private System.Nullable<double> GrossMarginField;
        
        private System.Nullable<System.DateTime> LikelyDeliveryDateField;
        
        private string MobileNumberField;
        
        private string OderIdField;
        
        private string OrderReasonsField;
        
        private System.Nullable<System.DateTime> OrderReferenceDateField;
        
        private string OrderReferenceIDField;
        
        private string OrderTypeField;
        
        private string PincodeField;
        
        private string PlantIDField;
        
        private string PlantNameField;
        
        private System.Nullable<System.DateTime> PoDateField;
        
        private string PoNoField;
        
        private string PriorityField;
        
        private string ProductRequiredField;
        
        private string ProjectNameField;
        
        private System.Nullable<System.DateTime> QuotationDateField;
        
        private string ReasonField;
        
        private string RegionField;
        
        private string RegionNameField;
        
        private string SAPOrderIDField;
        
        private string SalesOfficeField;
        
        private string StateField;
        
        private string StatusField;
        
        private string SubSegmentField;
        
        private string SubSegmentIDField;
        
        private string TempOrderIDField;
        
        private System.Nullable<double> TonnageField;
        
        private System.Nullable<double> TotalCostField;
        
        private System.Nullable<double> TotalValueField;
        
        private System.Nullable<double> TurnOverValueField;
        
        private string UserIDField;
        
        private string UsernameField;
        
        private string WonloseField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountID
        {
            get
            {
                return this.AccountIDField;
            }
            set
            {
                this.AccountIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountName
        {
            get
            {
                return this.AccountNameField;
            }
            set
            {
                this.AccountNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address1
        {
            get
            {
                return this.Address1Field;
            }
            set
            {
                this.Address1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Architect
        {
            get
            {
                return this.ArchitectField;
            }
            set
            {
                this.ArchitectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> BasicSaleValue
        {
            get
            {
                return this.BasicSaleValueField;
            }
            set
            {
                this.BasicSaleValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Branch
        {
            get
            {
                return this.BranchField;
            }
            set
            {
                this.BranchField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BranchName
        {
            get
            {
                return this.BranchNameField;
            }
            set
            {
                this.BranchNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BusinessSegment
        {
            get
            {
                return this.BusinessSegmentField;
            }
            set
            {
                this.BusinessSegmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BusinessSegmentID
        {
            get
            {
                return this.BusinessSegmentIDField;
            }
            set
            {
                this.BusinessSegmentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CRMLeadID
        {
            get
            {
                return this.CRMLeadIDField;
            }
            set
            {
                this.CRMLeadIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CRMOPPORTUNITYID
        {
            get
            {
                return this.CRMOPPORTUNITYIDField;
            }
            set
            {
                this.CRMOPPORTUNITYIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CRMOrderID
        {
            get
            {
                return this.CRMOrderIDField;
            }
            set
            {
                this.CRMOrderIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CRMQUOTATIONID
        {
            get
            {
                return this.CRMQUOTATIONIDField;
            }
            set
            {
                this.CRMQUOTATIONIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Channel
        {
            get
            {
                return this.ChannelField;
            }
            set
            {
                this.ChannelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Classification1
        {
            get
            {
                return this.Classification1Field;
            }
            set
            {
                this.Classification1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Classification2
        {
            get
            {
                return this.Classification2Field;
            }
            set
            {
                this.Classification2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Classification3
        {
            get
            {
                return this.Classification3Field;
            }
            set
            {
                this.Classification3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Classification3ID
        {
            get
            {
                return this.Classification3IDField;
            }
            set
            {
                this.Classification3IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Classification4
        {
            get
            {
                return this.Classification4Field;
            }
            set
            {
                this.Classification4Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompetitorName
        {
            get
            {
                return this.CompetitorNameField;
            }
            set
            {
                this.CompetitorNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> CompetitorPrice
        {
            get
            {
                return this.CompetitorPriceField;
            }
            set
            {
                this.CompetitorPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Consultant
        {
            get
            {
                return this.ConsultantField;
            }
            set
            {
                this.ConsultantField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactName
        {
            get
            {
                return this.ContactNameField;
            }
            set
            {
                this.ContactNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> ContractValue
        {
            get
            {
                return this.ContractValueField;
            }
            set
            {
                this.ContractValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency
        {
            get
            {
                return this.CurrencyField;
            }
            set
            {
                this.CurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> CurrencyValue
        {
            get
            {
                return this.CurrencyValueField;
            }
            set
            {
                this.CurrencyValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerClassification
        {
            get
            {
                return this.CustomerClassificationField;
            }
            set
            {
                this.CustomerClassificationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerClassificationId
        {
            get
            {
                return this.CustomerClassificationIdField;
            }
            set
            {
                this.CustomerClassificationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerSegment
        {
            get
            {
                return this.CustomerSegmentField;
            }
            set
            {
                this.CustomerSegmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerSegmentID
        {
            get
            {
                return this.CustomerSegmentIDField;
            }
            set
            {
                this.CustomerSegmentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerType
        {
            get
            {
                return this.CustomerTypeField;
            }
            set
            {
                this.CustomerTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerTypeID
        {
            get
            {
                return this.CustomerTypeIDField;
            }
            set
            {
                this.CustomerTypeIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Division
        {
            get
            {
                return this.DivisionField;
            }
            set
            {
                this.DivisionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DivisionName
        {
            get
            {
                return this.DivisionNameField;
            }
            set
            {
                this.DivisionNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DocumentCreatedDate
        {
            get
            {
                return this.DocumentCreatedDateField;
            }
            set
            {
                this.DocumentCreatedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EnquiryDate
        {
            get
            {
                return this.EnquiryDateField;
            }
            set
            {
                this.EnquiryDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> GrossMargin
        {
            get
            {
                return this.GrossMarginField;
            }
            set
            {
                this.GrossMarginField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LikelyDeliveryDate
        {
            get
            {
                return this.LikelyDeliveryDateField;
            }
            set
            {
                this.LikelyDeliveryDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileNumber
        {
            get
            {
                return this.MobileNumberField;
            }
            set
            {
                this.MobileNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OderId
        {
            get
            {
                return this.OderIdField;
            }
            set
            {
                this.OderIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderReasons
        {
            get
            {
                return this.OrderReasonsField;
            }
            set
            {
                this.OrderReasonsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> OrderReferenceDate
        {
            get
            {
                return this.OrderReferenceDateField;
            }
            set
            {
                this.OrderReferenceDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderReferenceID
        {
            get
            {
                return this.OrderReferenceIDField;
            }
            set
            {
                this.OrderReferenceIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderType
        {
            get
            {
                return this.OrderTypeField;
            }
            set
            {
                this.OrderTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pincode
        {
            get
            {
                return this.PincodeField;
            }
            set
            {
                this.PincodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlantID
        {
            get
            {
                return this.PlantIDField;
            }
            set
            {
                this.PlantIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlantName
        {
            get
            {
                return this.PlantNameField;
            }
            set
            {
                this.PlantNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PoDate
        {
            get
            {
                return this.PoDateField;
            }
            set
            {
                this.PoDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PoNo
        {
            get
            {
                return this.PoNoField;
            }
            set
            {
                this.PoNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Priority
        {
            get
            {
                return this.PriorityField;
            }
            set
            {
                this.PriorityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductRequired
        {
            get
            {
                return this.ProductRequiredField;
            }
            set
            {
                this.ProductRequiredField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProjectName
        {
            get
            {
                return this.ProjectNameField;
            }
            set
            {
                this.ProjectNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> QuotationDate
        {
            get
            {
                return this.QuotationDateField;
            }
            set
            {
                this.QuotationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason
        {
            get
            {
                return this.ReasonField;
            }
            set
            {
                this.ReasonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Region
        {
            get
            {
                return this.RegionField;
            }
            set
            {
                this.RegionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegionName
        {
            get
            {
                return this.RegionNameField;
            }
            set
            {
                this.RegionNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SAPOrderID
        {
            get
            {
                return this.SAPOrderIDField;
            }
            set
            {
                this.SAPOrderIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SalesOffice
        {
            get
            {
                return this.SalesOfficeField;
            }
            set
            {
                this.SalesOfficeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubSegment
        {
            get
            {
                return this.SubSegmentField;
            }
            set
            {
                this.SubSegmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubSegmentID
        {
            get
            {
                return this.SubSegmentIDField;
            }
            set
            {
                this.SubSegmentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TempOrderID
        {
            get
            {
                return this.TempOrderIDField;
            }
            set
            {
                this.TempOrderIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Tonnage
        {
            get
            {
                return this.TonnageField;
            }
            set
            {
                this.TonnageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> TotalCost
        {
            get
            {
                return this.TotalCostField;
            }
            set
            {
                this.TotalCostField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> TotalValue
        {
            get
            {
                return this.TotalValueField;
            }
            set
            {
                this.TotalValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> TurnOverValue
        {
            get
            {
                return this.TurnOverValueField;
            }
            set
            {
                this.TurnOverValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Wonlose
        {
            get
            {
                return this.WonloseField;
            }
            set
            {
                this.WonloseField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AGS_UploadContractValue", Namespace="http://schemas.datacontract.org/2004/07/SmartServe.BusinessLogicLayer.BusinessEnt" +
        "ities")]
    public partial class AGS_UploadContractValue : object
    {
        
        private System.Nullable<double> ContractValueField;
        
        private string DescriptionField;
        
        private string DocumentIdField;
        
        private string DocumentTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> ContractValue
        {
            get
            {
                return this.ContractValueField;
            }
            set
            {
                this.ContractValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentId
        {
            get
            {
                return this.DocumentIdField;
            }
            set
            {
                this.DocumentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentType
        {
            get
            {
                return this.DocumentTypeField;
            }
            set
            {
                this.DocumentTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CrmObjectReportRequest", Namespace="http://schemas.datacontract.org/2004/07/SmartServe.BusinessLogicLayer.BusinessEnt" +
        "ities")]
    public partial class CrmObjectReportRequest : object
    {
        
        private string BranchField;
        
        private string BusinessSegmentField;
        
        private string CompetitorField;
        
        private string CustomerGroupField;
        
        private string CustomerSegmentField;
        
        private string CustomerSubsegmentField;
        
        private System.Nullable<System.DateTime> DateFromField;
        
        private System.Nullable<System.DateTime> DateToField;
        
        private string DivisionField;
        
        private string DivisionNameField;
        
        private string DocumentIdField;
        
        private System.Nullable<System.DateTime> MaturityDateFromField;
        
        private System.Nullable<System.DateTime> MaturityDateToField;
        
        private string RegionField;
        
        private string RegionNameField;
        
        private string StatusField;
        
        private System.Nullable<double> ValueFromField;
        
        private System.Nullable<double> ValueToField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Branch
        {
            get
            {
                return this.BranchField;
            }
            set
            {
                this.BranchField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BusinessSegment
        {
            get
            {
                return this.BusinessSegmentField;
            }
            set
            {
                this.BusinessSegmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Competitor
        {
            get
            {
                return this.CompetitorField;
            }
            set
            {
                this.CompetitorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerGroup
        {
            get
            {
                return this.CustomerGroupField;
            }
            set
            {
                this.CustomerGroupField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerSegment
        {
            get
            {
                return this.CustomerSegmentField;
            }
            set
            {
                this.CustomerSegmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerSubsegment
        {
            get
            {
                return this.CustomerSubsegmentField;
            }
            set
            {
                this.CustomerSubsegmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateFrom
        {
            get
            {
                return this.DateFromField;
            }
            set
            {
                this.DateFromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateTo
        {
            get
            {
                return this.DateToField;
            }
            set
            {
                this.DateToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Division
        {
            get
            {
                return this.DivisionField;
            }
            set
            {
                this.DivisionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DivisionName
        {
            get
            {
                return this.DivisionNameField;
            }
            set
            {
                this.DivisionNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentId
        {
            get
            {
                return this.DocumentIdField;
            }
            set
            {
                this.DocumentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> MaturityDateFrom
        {
            get
            {
                return this.MaturityDateFromField;
            }
            set
            {
                this.MaturityDateFromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> MaturityDateTo
        {
            get
            {
                return this.MaturityDateToField;
            }
            set
            {
                this.MaturityDateToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Region
        {
            get
            {
                return this.RegionField;
            }
            set
            {
                this.RegionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegionName
        {
            get
            {
                return this.RegionNameField;
            }
            set
            {
                this.RegionNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> ValueFrom
        {
            get
            {
                return this.ValueFromField;
            }
            set
            {
                this.ValueFromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> ValueTo
        {
            get
            {
                return this.ValueToField;
            }
            set
            {
                this.ValueToField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WinlossReportRequest", Namespace="http://schemas.datacontract.org/2004/07/SmartServe.BusinessLogicLayer.BusinessEnt" +
        "ities")]
    public partial class WinlossReportRequest : object
    {
        
        private string BranchField;
        
        private string BusinessSegmentField;
        
        private string CompetitorField;
        
        private string CustomerGroupField;
        
        private string CustomerSegmentField;
        
        private string CustomerSubsegmentField;
        
        private System.Nullable<System.DateTime> DateFromField;
        
        private System.Nullable<System.DateTime> DateToField;
        
        private string DivisionField;
        
        private System.Nullable<System.DateTime> MaturityDateFromField;
        
        private System.Nullable<System.DateTime> MaturityDateToField;
        
        private string RegionField;
        
        private string StatusField;
        
        private System.Nullable<double> ValueFromField;
        
        private System.Nullable<double> ValueToField;
        
        private string WonloseField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Branch
        {
            get
            {
                return this.BranchField;
            }
            set
            {
                this.BranchField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BusinessSegment
        {
            get
            {
                return this.BusinessSegmentField;
            }
            set
            {
                this.BusinessSegmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Competitor
        {
            get
            {
                return this.CompetitorField;
            }
            set
            {
                this.CompetitorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerGroup
        {
            get
            {
                return this.CustomerGroupField;
            }
            set
            {
                this.CustomerGroupField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerSegment
        {
            get
            {
                return this.CustomerSegmentField;
            }
            set
            {
                this.CustomerSegmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerSubsegment
        {
            get
            {
                return this.CustomerSubsegmentField;
            }
            set
            {
                this.CustomerSubsegmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateFrom
        {
            get
            {
                return this.DateFromField;
            }
            set
            {
                this.DateFromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateTo
        {
            get
            {
                return this.DateToField;
            }
            set
            {
                this.DateToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Division
        {
            get
            {
                return this.DivisionField;
            }
            set
            {
                this.DivisionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> MaturityDateFrom
        {
            get
            {
                return this.MaturityDateFromField;
            }
            set
            {
                this.MaturityDateFromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> MaturityDateTo
        {
            get
            {
                return this.MaturityDateToField;
            }
            set
            {
                this.MaturityDateToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Region
        {
            get
            {
                return this.RegionField;
            }
            set
            {
                this.RegionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> ValueFrom
        {
            get
            {
                return this.ValueFromField;
            }
            set
            {
                this.ValueFromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> ValueTo
        {
            get
            {
                return this.ValueToField;
            }
            set
            {
                this.ValueToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Wonlose
        {
            get
            {
                return this.WonloseField;
            }
            set
            {
                this.WonloseField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrderProxy.IOrderProxyService")]
    public interface IOrderProxyService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderProxyService/RetrieveAll", ReplyAction="http://tempuri.org/IOrderProxyService/RetrieveAllResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<OrderProxy.AGS_Order>> RetrieveAllAsync(string sortBy, string sortOrder, int pageSize, string marker, int currentIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderProxyService/PagerCount", ReplyAction="http://tempuri.org/IOrderProxyService/PagerCountResponse")]
        System.Threading.Tasks.Task<int> PagerCountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderProxyService/Search", ReplyAction="http://tempuri.org/IOrderProxyService/SearchResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<OrderProxy.AGS_Order>> SearchAsync(string Key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderProxyService/SearchByStatus", ReplyAction="http://tempuri.org/IOrderProxyService/SearchByStatusResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<OrderProxy.AGS_Order>> SearchByStatusAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderProxyService/Retrieve", ReplyAction="http://tempuri.org/IOrderProxyService/RetrieveResponse")]
        System.Threading.Tasks.Task<OrderProxy.AGS_Order> RetrieveAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderProxyService/Create", ReplyAction="http://tempuri.org/IOrderProxyService/CreateResponse")]
        System.Threading.Tasks.Task<string> CreateAsync(OrderProxy.AGS_Order model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderProxyService/CreateMultiple", ReplyAction="http://tempuri.org/IOrderProxyService/CreateMultipleResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> CreateMultipleAsync(System.Collections.Generic.List<OrderProxy.AGS_Order> models);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderProxyService/Upload", ReplyAction="http://tempuri.org/IOrderProxyService/UploadResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> UploadAsync(System.Collections.Generic.List<OrderProxy.AGS_UploadOrder> models);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderProxyService/Update", ReplyAction="http://tempuri.org/IOrderProxyService/UpdateResponse")]
        System.Threading.Tasks.Task<bool> UpdateAsync(string id, OrderProxy.AGS_Order model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderProxyService/UploadContractValue", ReplyAction="http://tempuri.org/IOrderProxyService/UploadContractValueResponse")]
        System.Threading.Tasks.Task<bool> UploadContractValueAsync(OrderProxy.AGS_UploadContractValue model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderProxyService/Delete", ReplyAction="http://tempuri.org/IOrderProxyService/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderProxyService/ReportData", ReplyAction="http://tempuri.org/IOrderProxyService/ReportDataResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<OrderProxy.AGS_Order>> ReportDataAsync(OrderProxy.CrmObjectReportRequest model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderProxyService/WinlossReport", ReplyAction="http://tempuri.org/IOrderProxyService/WinlossReportResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<OrderProxy.AGS_Order>> WinlossReportAsync(OrderProxy.WinlossReportRequest model);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IOrderProxyServiceChannel : OrderProxy.IOrderProxyService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class OrderProxyServiceClient : System.ServiceModel.ClientBase<OrderProxy.IOrderProxyService>, OrderProxy.IOrderProxyService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public OrderProxyServiceClient() : 
                base(OrderProxyServiceClient.GetDefaultBinding(), OrderProxyServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.OrderProxySOAPEndPoint.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OrderProxyServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(OrderProxyServiceClient.GetBindingForEndpoint(endpointConfiguration), OrderProxyServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OrderProxyServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(OrderProxyServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OrderProxyServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(OrderProxyServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OrderProxyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<OrderProxy.AGS_Order>> RetrieveAllAsync(string sortBy, string sortOrder, int pageSize, string marker, int currentIndex)
        {
            return base.Channel.RetrieveAllAsync(sortBy, sortOrder, pageSize, marker, currentIndex);
        }
        
        public System.Threading.Tasks.Task<int> PagerCountAsync()
        {
            return base.Channel.PagerCountAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<OrderProxy.AGS_Order>> SearchAsync(string Key)
        {
            return base.Channel.SearchAsync(Key);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<OrderProxy.AGS_Order>> SearchByStatusAsync(string value)
        {
            return base.Channel.SearchByStatusAsync(value);
        }
        
        public System.Threading.Tasks.Task<OrderProxy.AGS_Order> RetrieveAsync(string id)
        {
            return base.Channel.RetrieveAsync(id);
        }
        
        public System.Threading.Tasks.Task<string> CreateAsync(OrderProxy.AGS_Order model)
        {
            return base.Channel.CreateAsync(model);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> CreateMultipleAsync(System.Collections.Generic.List<OrderProxy.AGS_Order> models)
        {
            return base.Channel.CreateMultipleAsync(models);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> UploadAsync(System.Collections.Generic.List<OrderProxy.AGS_UploadOrder> models)
        {
            return base.Channel.UploadAsync(models);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAsync(string id, OrderProxy.AGS_Order model)
        {
            return base.Channel.UpdateAsync(id, model);
        }
        
        public System.Threading.Tasks.Task<bool> UploadContractValueAsync(OrderProxy.AGS_UploadContractValue model)
        {
            return base.Channel.UploadContractValueAsync(model);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(string id)
        {
            return base.Channel.DeleteAsync(id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<OrderProxy.AGS_Order>> ReportDataAsync(OrderProxy.CrmObjectReportRequest model)
        {
            return base.Channel.ReportDataAsync(model);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<OrderProxy.AGS_Order>> WinlossReportAsync(OrderProxy.WinlossReportRequest model)
        {
            return base.Channel.WinlossReportAsync(model);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.OrderProxySOAPEndPoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.OrderProxySOAPEndPoint))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.10.146/GateKeeper/Proxy/OrderProxyService.svc/SOAP");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return OrderProxyServiceClient.GetBindingForEndpoint(EndpointConfiguration.OrderProxySOAPEndPoint);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return OrderProxyServiceClient.GetEndpointAddress(EndpointConfiguration.OrderProxySOAPEndPoint);
        }
        
        public enum EndpointConfiguration
        {
            
            OrderProxySOAPEndPoint,
        }
    }
}
