//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeadProxy
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AGS_Lead", Namespace="http://schemas.datacontract.org/2004/07/SmartServe.BusinessLogicLayer.BusinessEnt" +
        "ities")]
    public partial class AGS_Lead : object
    {
        
        private string AccountIDField;
        
        private string AccountNameField;
        
        private string Address1Field;
        
        private string ArchitectField;
        
        private string BranchField;
        
        private string BranchNameField;
        
        private string BusinessSegmentField;
        
        private string BusinessSegmentIDField;
        
        private string CRMLeadIDField;
        
        private string ChannelField;
        
        private string CityField;
        
        private string Classificaiton3idField;
        
        private string Classification1Field;
        
        private string Classification2Field;
        
        private string Classification3Field;
        
        private string Classification4Field;
        
        private string ConsultantField;
        
        private string ContactNameField;
        
        private System.Nullable<double> ContractValueField;
        
        private string CreatedByField;
        
        private System.Nullable<System.DateTime> CreatedOnField;
        
        private string CurrencyField;
        
        private System.Nullable<double> CurrencyValueField;
        
        private string CustomerClassificationField;
        
        private string CustomerClassificationIdField;
        
        private string CustomerSegmentField;
        
        private string CustomerSegmentIDField;
        
        private string CustomerTypeField;
        
        private string CustomerTypeIDField;
        
        private string DescriptionField;
        
        private string DivisionField;
        
        private string DivisionNameField;
        
        private System.Nullable<System.DateTime> DocumentCreatedDateField;
        
        private System.Nullable<System.DateTime> LeadMaturityDateField;
        
        private string MobileNumberField;
        
        private string ModifiedByField;
        
        private System.Nullable<System.DateTime> ModifiedOnField;
        
        private string ObjectTypeField;
        
        private string PincodeField;
        
        private string PlantIDField;
        
        private string PlantNameField;
        
        private string PriorityField;
        
        private string ProbabilityField;
        
        private string ProductRequiredField;
        
        private string ProjectNameField;
        
        private string ReasonField;
        
        private string RegionField;
        
        private string RegionNameField;
        
        private string SAPLeadIDField;
        
        private string SalesOfficeField;
        
        private string SourceTypeField;
        
        private string StateField;
        
        private string StatusField;
        
        private string SubSegmentField;
        
        private string SubSegmentIDField;
        
        private string TempLeadIDField;
        
        private string UserIDField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountID
        {
            get
            {
                return this.AccountIDField;
            }
            set
            {
                this.AccountIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountName
        {
            get
            {
                return this.AccountNameField;
            }
            set
            {
                this.AccountNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address1
        {
            get
            {
                return this.Address1Field;
            }
            set
            {
                this.Address1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Architect
        {
            get
            {
                return this.ArchitectField;
            }
            set
            {
                this.ArchitectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Branch
        {
            get
            {
                return this.BranchField;
            }
            set
            {
                this.BranchField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BranchName
        {
            get
            {
                return this.BranchNameField;
            }
            set
            {
                this.BranchNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BusinessSegment
        {
            get
            {
                return this.BusinessSegmentField;
            }
            set
            {
                this.BusinessSegmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BusinessSegmentID
        {
            get
            {
                return this.BusinessSegmentIDField;
            }
            set
            {
                this.BusinessSegmentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CRMLeadID
        {
            get
            {
                return this.CRMLeadIDField;
            }
            set
            {
                this.CRMLeadIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Channel
        {
            get
            {
                return this.ChannelField;
            }
            set
            {
                this.ChannelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Classificaiton3id
        {
            get
            {
                return this.Classificaiton3idField;
            }
            set
            {
                this.Classificaiton3idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Classification1
        {
            get
            {
                return this.Classification1Field;
            }
            set
            {
                this.Classification1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Classification2
        {
            get
            {
                return this.Classification2Field;
            }
            set
            {
                this.Classification2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Classification3
        {
            get
            {
                return this.Classification3Field;
            }
            set
            {
                this.Classification3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Classification4
        {
            get
            {
                return this.Classification4Field;
            }
            set
            {
                this.Classification4Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Consultant
        {
            get
            {
                return this.ConsultantField;
            }
            set
            {
                this.ConsultantField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactName
        {
            get
            {
                return this.ContactNameField;
            }
            set
            {
                this.ContactNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> ContractValue
        {
            get
            {
                return this.ContractValueField;
            }
            set
            {
                this.ContractValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this.CreatedByField;
            }
            set
            {
                this.CreatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedOn
        {
            get
            {
                return this.CreatedOnField;
            }
            set
            {
                this.CreatedOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency
        {
            get
            {
                return this.CurrencyField;
            }
            set
            {
                this.CurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> CurrencyValue
        {
            get
            {
                return this.CurrencyValueField;
            }
            set
            {
                this.CurrencyValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerClassification
        {
            get
            {
                return this.CustomerClassificationField;
            }
            set
            {
                this.CustomerClassificationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerClassificationId
        {
            get
            {
                return this.CustomerClassificationIdField;
            }
            set
            {
                this.CustomerClassificationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerSegment
        {
            get
            {
                return this.CustomerSegmentField;
            }
            set
            {
                this.CustomerSegmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerSegmentID
        {
            get
            {
                return this.CustomerSegmentIDField;
            }
            set
            {
                this.CustomerSegmentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerType
        {
            get
            {
                return this.CustomerTypeField;
            }
            set
            {
                this.CustomerTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerTypeID
        {
            get
            {
                return this.CustomerTypeIDField;
            }
            set
            {
                this.CustomerTypeIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Division
        {
            get
            {
                return this.DivisionField;
            }
            set
            {
                this.DivisionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DivisionName
        {
            get
            {
                return this.DivisionNameField;
            }
            set
            {
                this.DivisionNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DocumentCreatedDate
        {
            get
            {
                return this.DocumentCreatedDateField;
            }
            set
            {
                this.DocumentCreatedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LeadMaturityDate
        {
            get
            {
                return this.LeadMaturityDateField;
            }
            set
            {
                this.LeadMaturityDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileNumber
        {
            get
            {
                return this.MobileNumberField;
            }
            set
            {
                this.MobileNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy
        {
            get
            {
                return this.ModifiedByField;
            }
            set
            {
                this.ModifiedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ModifiedOn
        {
            get
            {
                return this.ModifiedOnField;
            }
            set
            {
                this.ModifiedOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObjectType
        {
            get
            {
                return this.ObjectTypeField;
            }
            set
            {
                this.ObjectTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pincode
        {
            get
            {
                return this.PincodeField;
            }
            set
            {
                this.PincodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlantID
        {
            get
            {
                return this.PlantIDField;
            }
            set
            {
                this.PlantIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlantName
        {
            get
            {
                return this.PlantNameField;
            }
            set
            {
                this.PlantNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Priority
        {
            get
            {
                return this.PriorityField;
            }
            set
            {
                this.PriorityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Probability
        {
            get
            {
                return this.ProbabilityField;
            }
            set
            {
                this.ProbabilityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductRequired
        {
            get
            {
                return this.ProductRequiredField;
            }
            set
            {
                this.ProductRequiredField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProjectName
        {
            get
            {
                return this.ProjectNameField;
            }
            set
            {
                this.ProjectNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason
        {
            get
            {
                return this.ReasonField;
            }
            set
            {
                this.ReasonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Region
        {
            get
            {
                return this.RegionField;
            }
            set
            {
                this.RegionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegionName
        {
            get
            {
                return this.RegionNameField;
            }
            set
            {
                this.RegionNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SAPLeadID
        {
            get
            {
                return this.SAPLeadIDField;
            }
            set
            {
                this.SAPLeadIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SalesOffice
        {
            get
            {
                return this.SalesOfficeField;
            }
            set
            {
                this.SalesOfficeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SourceType
        {
            get
            {
                return this.SourceTypeField;
            }
            set
            {
                this.SourceTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubSegment
        {
            get
            {
                return this.SubSegmentField;
            }
            set
            {
                this.SubSegmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubSegmentID
        {
            get
            {
                return this.SubSegmentIDField;
            }
            set
            {
                this.SubSegmentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TempLeadID
        {
            get
            {
                return this.TempLeadIDField;
            }
            set
            {
                this.TempLeadIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AGS_LeadHistory", Namespace="http://schemas.datacontract.org/2004/07/SmartServe.BusinessLogicLayer.BusinessEnt" +
        "ities")]
    public partial class AGS_LeadHistory : object
    {
        
        private string CRMLeadIDField;
        
        private string CreatedByField;
        
        private System.Nullable<System.DateTime> CreatedOnField;
        
        private string RemarksField;
        
        private string StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CRMLeadID
        {
            get
            {
                return this.CRMLeadIDField;
            }
            set
            {
                this.CRMLeadIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this.CreatedByField;
            }
            set
            {
                this.CreatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedOn
        {
            get
            {
                return this.CreatedOnField;
            }
            set
            {
                this.CreatedOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remarks
        {
            get
            {
                return this.RemarksField;
            }
            set
            {
                this.RemarksField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CrmObjectReportRequest", Namespace="http://schemas.datacontract.org/2004/07/SmartServe.BusinessLogicLayer.BusinessEnt" +
        "ities")]
    public partial class CrmObjectReportRequest : object
    {
        
        private string BranchField;
        
        private string BusinessSegmentField;
        
        private string CompetitorField;
        
        private string CustomerGroupField;
        
        private string CustomerSegmentField;
        
        private string CustomerSubsegmentField;
        
        private System.Nullable<System.DateTime> DateFromField;
        
        private System.Nullable<System.DateTime> DateToField;
        
        private string DivisionField;
        
        private string DivisionNameField;
        
        private System.Nullable<System.DateTime> MaturityDateFromField;
        
        private System.Nullable<System.DateTime> MaturityDateToField;
        
        private string RegionField;
        
        private string RegionNameField;
        
        private string StatusField;
        
        private System.Nullable<double> ValueFromField;
        
        private System.Nullable<double> ValueToField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Branch
        {
            get
            {
                return this.BranchField;
            }
            set
            {
                this.BranchField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BusinessSegment
        {
            get
            {
                return this.BusinessSegmentField;
            }
            set
            {
                this.BusinessSegmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Competitor
        {
            get
            {
                return this.CompetitorField;
            }
            set
            {
                this.CompetitorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerGroup
        {
            get
            {
                return this.CustomerGroupField;
            }
            set
            {
                this.CustomerGroupField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerSegment
        {
            get
            {
                return this.CustomerSegmentField;
            }
            set
            {
                this.CustomerSegmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerSubsegment
        {
            get
            {
                return this.CustomerSubsegmentField;
            }
            set
            {
                this.CustomerSubsegmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateFrom
        {
            get
            {
                return this.DateFromField;
            }
            set
            {
                this.DateFromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateTo
        {
            get
            {
                return this.DateToField;
            }
            set
            {
                this.DateToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Division
        {
            get
            {
                return this.DivisionField;
            }
            set
            {
                this.DivisionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DivisionName
        {
            get
            {
                return this.DivisionNameField;
            }
            set
            {
                this.DivisionNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> MaturityDateFrom
        {
            get
            {
                return this.MaturityDateFromField;
            }
            set
            {
                this.MaturityDateFromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> MaturityDateTo
        {
            get
            {
                return this.MaturityDateToField;
            }
            set
            {
                this.MaturityDateToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Region
        {
            get
            {
                return this.RegionField;
            }
            set
            {
                this.RegionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegionName
        {
            get
            {
                return this.RegionNameField;
            }
            set
            {
                this.RegionNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> ValueFrom
        {
            get
            {
                return this.ValueFromField;
            }
            set
            {
                this.ValueFromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> ValueTo
        {
            get
            {
                return this.ValueToField;
            }
            set
            {
                this.ValueToField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LeadProxy.ILeadProxyService")]
    public interface ILeadProxyService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeadProxyService/RetrieveAll", ReplyAction="http://tempuri.org/ILeadProxyService/RetrieveAllResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<LeadProxy.AGS_Lead>> RetrieveAllAsync(string sortBy, string sortOrder, int pageSize, string marker, int currentIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeadProxyService/PagerCount", ReplyAction="http://tempuri.org/ILeadProxyService/PagerCountResponse")]
        System.Threading.Tasks.Task<int> PagerCountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeadProxyService/Search", ReplyAction="http://tempuri.org/ILeadProxyService/SearchResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<LeadProxy.AGS_Lead>> SearchAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeadProxyService/SearchByStatus", ReplyAction="http://tempuri.org/ILeadProxyService/SearchByStatusResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<LeadProxy.AGS_Lead>> SearchByStatusAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeadProxyService/Retrieve", ReplyAction="http://tempuri.org/ILeadProxyService/RetrieveResponse")]
        System.Threading.Tasks.Task<LeadProxy.AGS_Lead> RetrieveAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeadProxyService/Create", ReplyAction="http://tempuri.org/ILeadProxyService/CreateResponse")]
        System.Threading.Tasks.Task<string> CreateAsync(LeadProxy.AGS_Lead model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeadProxyService/Update", ReplyAction="http://tempuri.org/ILeadProxyService/UpdateResponse")]
        System.Threading.Tasks.Task<bool> UpdateAsync(string id, LeadProxy.AGS_Lead model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeadProxyService/Delete", ReplyAction="http://tempuri.org/ILeadProxyService/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeadProxyService/History", ReplyAction="http://tempuri.org/ILeadProxyService/HistoryResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<LeadProxy.AGS_LeadHistory>> HistoryAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeadProxyService/ReportData", ReplyAction="http://tempuri.org/ILeadProxyService/ReportDataResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<LeadProxy.AGS_Lead>> ReportDataAsync(LeadProxy.CrmObjectReportRequest model);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    public interface ILeadProxyServiceChannel : LeadProxy.ILeadProxyService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    public partial class LeadProxyServiceClient : System.ServiceModel.ClientBase<LeadProxy.ILeadProxyService>, LeadProxy.ILeadProxyService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public LeadProxyServiceClient() : 
                base(LeadProxyServiceClient.GetDefaultBinding(), LeadProxyServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.LeadProxySOAPEndPoint.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LeadProxyServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(LeadProxyServiceClient.GetBindingForEndpoint(endpointConfiguration), LeadProxyServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LeadProxyServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(LeadProxyServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LeadProxyServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(LeadProxyServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LeadProxyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<LeadProxy.AGS_Lead>> RetrieveAllAsync(string sortBy, string sortOrder, int pageSize, string marker, int currentIndex)
        {
            return base.Channel.RetrieveAllAsync(sortBy, sortOrder, pageSize, marker, currentIndex);
        }
        
        public System.Threading.Tasks.Task<int> PagerCountAsync()
        {
            return base.Channel.PagerCountAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<LeadProxy.AGS_Lead>> SearchAsync(string value)
        {
            return base.Channel.SearchAsync(value);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<LeadProxy.AGS_Lead>> SearchByStatusAsync(string value)
        {
            return base.Channel.SearchByStatusAsync(value);
        }
        
        public System.Threading.Tasks.Task<LeadProxy.AGS_Lead> RetrieveAsync(string id)
        {
            return base.Channel.RetrieveAsync(id);
        }
        
        public System.Threading.Tasks.Task<string> CreateAsync(LeadProxy.AGS_Lead model)
        {
            return base.Channel.CreateAsync(model);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAsync(string id, LeadProxy.AGS_Lead model)
        {
            return base.Channel.UpdateAsync(id, model);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(string id)
        {
            return base.Channel.DeleteAsync(id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<LeadProxy.AGS_LeadHistory>> HistoryAsync(string id)
        {
            return base.Channel.HistoryAsync(id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<LeadProxy.AGS_Lead>> ReportDataAsync(LeadProxy.CrmObjectReportRequest model)
        {
            return base.Channel.ReportDataAsync(model);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LeadProxySOAPEndPoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LeadProxySOAPEndPoint))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.10.145/GateKeeper/Proxy/LeadProxyService.svc/SOAP");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return LeadProxyServiceClient.GetBindingForEndpoint(EndpointConfiguration.LeadProxySOAPEndPoint);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return LeadProxyServiceClient.GetEndpointAddress(EndpointConfiguration.LeadProxySOAPEndPoint);
        }
        
        public enum EndpointConfiguration
        {
            
            LeadProxySOAPEndPoint,
        }
    }
}
