//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocationProxy
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AGS_Location", Namespace="http://schemas.datacontract.org/2004/07/SmartServe.BusinessLogicLayer.BusinessEnt" +
        "ities")]
    public partial class AGS_Location : object
    {
        
        private System.Collections.Generic.List<LocationProxy.AGS_Location_Branch> BranchesField;
        
        private System.Collections.Generic.List<LocationProxy.AGS_Location_Division> DivisionsField;
        
        private System.Collections.Generic.List<LocationProxy.AGS_Location_Plant> PlantsField;
        
        private System.Collections.Generic.List<LocationProxy.AGS_Location_Region> RegionsField;
        
        private System.Collections.Generic.List<LocationProxy.AGS_Location_SalesOffice> SalesOfficesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<LocationProxy.AGS_Location_Branch> Branches
        {
            get
            {
                return this.BranchesField;
            }
            set
            {
                this.BranchesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<LocationProxy.AGS_Location_Division> Divisions
        {
            get
            {
                return this.DivisionsField;
            }
            set
            {
                this.DivisionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<LocationProxy.AGS_Location_Plant> Plants
        {
            get
            {
                return this.PlantsField;
            }
            set
            {
                this.PlantsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<LocationProxy.AGS_Location_Region> Regions
        {
            get
            {
                return this.RegionsField;
            }
            set
            {
                this.RegionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<LocationProxy.AGS_Location_SalesOffice> SalesOffices
        {
            get
            {
                return this.SalesOfficesField;
            }
            set
            {
                this.SalesOfficesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AGS_Location_Branch", Namespace="http://schemas.datacontract.org/2004/07/SmartServe.BusinessLogicLayer.BusinessEnt" +
        "ities")]
    public partial class AGS_Location_Branch : object
    {
        
        private string IDField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AGS_Location_Division", Namespace="http://schemas.datacontract.org/2004/07/SmartServe.BusinessLogicLayer.BusinessEnt" +
        "ities")]
    public partial class AGS_Location_Division : object
    {
        
        private string IDField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AGS_Location_Plant", Namespace="http://schemas.datacontract.org/2004/07/SmartServe.BusinessLogicLayer.BusinessEnt" +
        "ities")]
    public partial class AGS_Location_Plant : object
    {
        
        private string CodeField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AGS_Location_Region", Namespace="http://schemas.datacontract.org/2004/07/SmartServe.BusinessLogicLayer.BusinessEnt" +
        "ities")]
    public partial class AGS_Location_Region : object
    {
        
        private string IDField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AGS_Location_SalesOffice", Namespace="http://schemas.datacontract.org/2004/07/SmartServe.BusinessLogicLayer.BusinessEnt" +
        "ities")]
    public partial class AGS_Location_SalesOffice : object
    {
        
        private string CodeField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LocationProxy.ILocationProxyService")]
    public interface ILocationProxyService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocationProxyService/RetrieveLocationDetails", ReplyAction="http://tempuri.org/ILocationProxyService/RetrieveLocationDetailsResponse")]
        System.Threading.Tasks.Task<LocationProxy.AGS_Location> RetrieveLocationDetailsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocationProxyService/RetrieveLocationDetailsByOrg", ReplyAction="http://tempuri.org/ILocationProxyService/RetrieveLocationDetailsByOrgResponse")]
        System.Threading.Tasks.Task<LocationProxy.AGS_Location> RetrieveLocationDetailsByOrgAsync(string orgId, string clientId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ILocationProxyServiceChannel : LocationProxy.ILocationProxyService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class LocationProxyServiceClient : System.ServiceModel.ClientBase<LocationProxy.ILocationProxyService>, LocationProxy.ILocationProxyService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public LocationProxyServiceClient() : 
                base(LocationProxyServiceClient.GetDefaultBinding(), LocationProxyServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.LocationProxySOAPEndPoint.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LocationProxyServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(LocationProxyServiceClient.GetBindingForEndpoint(endpointConfiguration), LocationProxyServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LocationProxyServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(LocationProxyServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LocationProxyServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(LocationProxyServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LocationProxyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<LocationProxy.AGS_Location> RetrieveLocationDetailsAsync()
        {
            return base.Channel.RetrieveLocationDetailsAsync();
        }
        
        public System.Threading.Tasks.Task<LocationProxy.AGS_Location> RetrieveLocationDetailsByOrgAsync(string orgId, string clientId)
        {
            return base.Channel.RetrieveLocationDetailsByOrgAsync(orgId, clientId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LocationProxySOAPEndPoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LocationProxySOAPEndPoint))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/GateKeeper/Proxy/LocationProxyService.svc/SOAP");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return LocationProxyServiceClient.GetBindingForEndpoint(EndpointConfiguration.LocationProxySOAPEndPoint);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return LocationProxyServiceClient.GetEndpointAddress(EndpointConfiguration.LocationProxySOAPEndPoint);
        }
        
        public enum EndpointConfiguration
        {
            
            LocationProxySOAPEndPoint,
        }
    }
}
