//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityMapProxy
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AGS_EntityMap", Namespace="http://schemas.datacontract.org/2004/07/SmartServe.BusinessLogicLayer.BusinessEnt" +
        "ities")]
    public partial class AGS_EntityMap : object
    {
        
        private string AttributeNameField;
        
        private string CreatedByField;
        
        private System.Nullable<System.DateTime> CreatedOnField;
        
        private string EntityMapIDField;
        
        private string ModifiedByField;
        
        private System.Nullable<System.DateTime> ModifiedOnField;
        
        private string ObjectTypeField;
        
        private string ObjectTypeNameField;
        
        private string ParentPropertyValueField;
        
        private string PropertyNameField;
        
        private string PropertyValueField;
        
        private string StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AttributeName
        {
            get
            {
                return this.AttributeNameField;
            }
            set
            {
                this.AttributeNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this.CreatedByField;
            }
            set
            {
                this.CreatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedOn
        {
            get
            {
                return this.CreatedOnField;
            }
            set
            {
                this.CreatedOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityMapID
        {
            get
            {
                return this.EntityMapIDField;
            }
            set
            {
                this.EntityMapIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy
        {
            get
            {
                return this.ModifiedByField;
            }
            set
            {
                this.ModifiedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ModifiedOn
        {
            get
            {
                return this.ModifiedOnField;
            }
            set
            {
                this.ModifiedOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObjectType
        {
            get
            {
                return this.ObjectTypeField;
            }
            set
            {
                this.ObjectTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObjectTypeName
        {
            get
            {
                return this.ObjectTypeNameField;
            }
            set
            {
                this.ObjectTypeNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParentPropertyValue
        {
            get
            {
                return this.ParentPropertyValueField;
            }
            set
            {
                this.ParentPropertyValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PropertyName
        {
            get
            {
                return this.PropertyNameField;
            }
            set
            {
                this.PropertyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PropertyValue
        {
            get
            {
                return this.PropertyValueField;
            }
            set
            {
                this.PropertyValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EntityMapProxy.IEntityMapProxyService")]
    public interface IEntityMapProxyService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityMapProxyService/RetrieveAll", ReplyAction="http://tempuri.org/IEntityMapProxyService/RetrieveAllResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<EntityMapProxy.AGS_EntityMap>> RetrieveAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityMapProxyService/RetrieveByObjectName", ReplyAction="http://tempuri.org/IEntityMapProxyService/RetrieveByObjectNameResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<EntityMapProxy.AGS_EntityMap>> RetrieveByObjectNameAsync(string objectName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityMapProxyService/RetrieveByAttributeName", ReplyAction="http://tempuri.org/IEntityMapProxyService/RetrieveByAttributeNameResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<EntityMapProxy.AGS_EntityMap>> RetrieveByAttributeNameAsync(string objectName, string attributeName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityMapProxyService/RetrieveByParent", ReplyAction="http://tempuri.org/IEntityMapProxyService/RetrieveByParentResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<EntityMapProxy.AGS_EntityMap>> RetrieveByParentAsync(string objectName, string attributeName, string parent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityMapProxyService/RetrieveByID", ReplyAction="http://tempuri.org/IEntityMapProxyService/RetrieveByIDResponse")]
        System.Threading.Tasks.Task<EntityMapProxy.AGS_EntityMap> RetrieveByIDAsync(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    public interface IEntityMapProxyServiceChannel : EntityMapProxy.IEntityMapProxyService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    public partial class EntityMapProxyServiceClient : System.ServiceModel.ClientBase<EntityMapProxy.IEntityMapProxyService>, EntityMapProxy.IEntityMapProxyService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public EntityMapProxyServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(EntityMapProxyServiceClient.GetBindingForEndpoint(endpointConfiguration), EntityMapProxyServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EntityMapProxyServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(EntityMapProxyServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EntityMapProxyServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(EntityMapProxyServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EntityMapProxyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<EntityMapProxy.AGS_EntityMap>> RetrieveAllAsync()
        {
            return base.Channel.RetrieveAllAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<EntityMapProxy.AGS_EntityMap>> RetrieveByObjectNameAsync(string objectName)
        {
            return base.Channel.RetrieveByObjectNameAsync(objectName);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<EntityMapProxy.AGS_EntityMap>> RetrieveByAttributeNameAsync(string objectName, string attributeName)
        {
            return base.Channel.RetrieveByAttributeNameAsync(objectName, attributeName);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<EntityMapProxy.AGS_EntityMap>> RetrieveByParentAsync(string objectName, string attributeName, string parent)
        {
            return base.Channel.RetrieveByParentAsync(objectName, attributeName, parent);
        }
        
        public System.Threading.Tasks.Task<EntityMapProxy.AGS_EntityMap> RetrieveByIDAsync(string id)
        {
            return base.Channel.RetrieveByIDAsync(id);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.EntityMapProxySOAPEndPoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.EntityMapProxySOAPHttpsEndPoint))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.EntityMapProxySOAPEndPoint))
            {
                return new System.ServiceModel.EndpointAddress("http://ps-win-cscrmqty.voltasworld.com/GateKeeper/Proxy/EntityMapProxyService.svc" +
                        "/SOAP");
            }
            if ((endpointConfiguration == EndpointConfiguration.EntityMapProxySOAPHttpsEndPoint))
            {
                return new System.ServiceModel.EndpointAddress("https://vserveq.voltasworld.com/GateKeeper/Proxy/EntityMapProxyService.svc/SOAP");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            EntityMapProxySOAPEndPoint,
            
            EntityMapProxySOAPHttpsEndPoint,
        }
    }
}
