//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientProxy
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AGS_Client", Namespace="http://schemas.datacontract.org/2004/07/SmartServe.BusinessLogicLayer.BusinessEnt" +
        "ities")]
    public partial class AGS_Client : object
    {
        
        private string AccNoField;
        
        private string ActiveUsersField;
        
        private string AddressField;
        
        private string BackendField;
        
        private string BankNameField;
        
        private string BranchField;
        
        private string ClientIDField;
        
        private string ClientLogonNameField;
        
        private string ClientTypeField;
        
        private string ContactIDField;
        
        private string CorpAddressField;
        
        private string CountryField;
        
        private string CreatedByField;
        
        private ClientProxy.EntityState EntityStateField;
        
        private string EstablishedField;
        
        private string FaxField;
        
        private string IndustryField;
        
        private string LanguageField;
        
        private string LicenseNoField;
        
        private string LicenseTypeField;
        
        private string LogoField;
        
        private string Mail1Field;
        
        private string Mail2Field;
        
        private string NOOFEMPLOYEESField;
        
        private string NameField;
        
        private string ObjectTypeField;
        
        private string PANNOField;
        
        private string Phone1Field;
        
        private string Phone2Field;
        
        private string Phone3Field;
        
        private System.Nullable<System.DateTime> PhysicalEndField;
        
        private System.Nullable<System.DateTime> PhysicalStartField;
        
        private string RegAddressField;
        
        private string RegionField;
        
        private string SolutionField;
        
        private string StateField;
        
        private string StatusField;
        
        private string TANNOField;
        
        private string TechnologyField;
        
        private string TypeOfAccountField;
        
        private string VATNOField;
        
        private System.Nullable<System.DateTime> ValidFromField;
        
        private System.Nullable<System.DateTime> ValidToField;
        
        private string WEBSITEField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccNo
        {
            get
            {
                return this.AccNoField;
            }
            set
            {
                this.AccNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActiveUsers
        {
            get
            {
                return this.ActiveUsersField;
            }
            set
            {
                this.ActiveUsersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Backend
        {
            get
            {
                return this.BackendField;
            }
            set
            {
                this.BackendField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankName
        {
            get
            {
                return this.BankNameField;
            }
            set
            {
                this.BankNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Branch
        {
            get
            {
                return this.BranchField;
            }
            set
            {
                this.BranchField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientID
        {
            get
            {
                return this.ClientIDField;
            }
            set
            {
                this.ClientIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientLogonName
        {
            get
            {
                return this.ClientLogonNameField;
            }
            set
            {
                this.ClientLogonNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientType
        {
            get
            {
                return this.ClientTypeField;
            }
            set
            {
                this.ClientTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactID
        {
            get
            {
                return this.ContactIDField;
            }
            set
            {
                this.ContactIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorpAddress
        {
            get
            {
                return this.CorpAddressField;
            }
            set
            {
                this.CorpAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                this.CountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this.CreatedByField;
            }
            set
            {
                this.CreatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientProxy.EntityState EntityState
        {
            get
            {
                return this.EntityStateField;
            }
            set
            {
                this.EntityStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Established
        {
            get
            {
                return this.EstablishedField;
            }
            set
            {
                this.EstablishedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fax
        {
            get
            {
                return this.FaxField;
            }
            set
            {
                this.FaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Industry
        {
            get
            {
                return this.IndustryField;
            }
            set
            {
                this.IndustryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language
        {
            get
            {
                return this.LanguageField;
            }
            set
            {
                this.LanguageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LicenseNo
        {
            get
            {
                return this.LicenseNoField;
            }
            set
            {
                this.LicenseNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LicenseType
        {
            get
            {
                return this.LicenseTypeField;
            }
            set
            {
                this.LicenseTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Logo
        {
            get
            {
                return this.LogoField;
            }
            set
            {
                this.LogoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mail1
        {
            get
            {
                return this.Mail1Field;
            }
            set
            {
                this.Mail1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mail2
        {
            get
            {
                return this.Mail2Field;
            }
            set
            {
                this.Mail2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOOFEMPLOYEES
        {
            get
            {
                return this.NOOFEMPLOYEESField;
            }
            set
            {
                this.NOOFEMPLOYEESField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObjectType
        {
            get
            {
                return this.ObjectTypeField;
            }
            set
            {
                this.ObjectTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PANNO
        {
            get
            {
                return this.PANNOField;
            }
            set
            {
                this.PANNOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone1
        {
            get
            {
                return this.Phone1Field;
            }
            set
            {
                this.Phone1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone2
        {
            get
            {
                return this.Phone2Field;
            }
            set
            {
                this.Phone2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone3
        {
            get
            {
                return this.Phone3Field;
            }
            set
            {
                this.Phone3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PhysicalEnd
        {
            get
            {
                return this.PhysicalEndField;
            }
            set
            {
                this.PhysicalEndField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PhysicalStart
        {
            get
            {
                return this.PhysicalStartField;
            }
            set
            {
                this.PhysicalStartField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegAddress
        {
            get
            {
                return this.RegAddressField;
            }
            set
            {
                this.RegAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Region
        {
            get
            {
                return this.RegionField;
            }
            set
            {
                this.RegionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Solution
        {
            get
            {
                return this.SolutionField;
            }
            set
            {
                this.SolutionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TANNO
        {
            get
            {
                return this.TANNOField;
            }
            set
            {
                this.TANNOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Technology
        {
            get
            {
                return this.TechnologyField;
            }
            set
            {
                this.TechnologyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeOfAccount
        {
            get
            {
                return this.TypeOfAccountField;
            }
            set
            {
                this.TypeOfAccountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VATNO
        {
            get
            {
                return this.VATNOField;
            }
            set
            {
                this.VATNOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ValidFrom
        {
            get
            {
                return this.ValidFromField;
            }
            set
            {
                this.ValidFromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ValidTo
        {
            get
            {
                return this.ValidToField;
            }
            set
            {
                this.ValidToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WEBSITE
        {
            get
            {
                return this.WEBSITEField;
            }
            set
            {
                this.WEBSITEField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityState", Namespace="http://schemas.datacontract.org/2004/07/SmartServe.BusinessLogicLayer")]
    public enum EntityState : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unchanged = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Added = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Modified = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deleted = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AGS_DropdownEntity", Namespace="http://schemas.datacontract.org/2004/07/SmartServe.BusinessLogicLayer.BusinessEnt" +
        "ities")]
    public partial class AGS_DropdownEntity : object
    {
        
        private string TextField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text
        {
            get
            {
                return this.TextField;
            }
            set
            {
                this.TextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClientProxy.IClientProxyService")]
    public interface IClientProxyService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientProxyService/RetrieveAll", ReplyAction="http://tempuri.org/IClientProxyService/RetrieveAllResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ClientProxy.AGS_Client>> RetrieveAllAsync(string sortBy, string sortOrder, int pageSize, string marker, int currentIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientProxyService/PagerCount", ReplyAction="http://tempuri.org/IClientProxyService/PagerCountResponse")]
        System.Threading.Tasks.Task<int> PagerCountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientProxyService/Search", ReplyAction="http://tempuri.org/IClientProxyService/SearchResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ClientProxy.AGS_Client>> SearchAsync(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientProxyService/Retrieve", ReplyAction="http://tempuri.org/IClientProxyService/RetrieveResponse")]
        System.Threading.Tasks.Task<ClientProxy.AGS_Client> RetrieveAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientProxyService/Create", ReplyAction="http://tempuri.org/IClientProxyService/CreateResponse")]
        System.Threading.Tasks.Task<string> CreateAsync(ClientProxy.AGS_Client user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientProxyService/Update", ReplyAction="http://tempuri.org/IClientProxyService/UpdateResponse")]
        System.Threading.Tasks.Task<bool> UpdateAsync(string id, ClientProxy.AGS_Client model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientProxyService/Delete", ReplyAction="http://tempuri.org/IClientProxyService/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientProxyService/FillClients", ReplyAction="http://tempuri.org/IClientProxyService/FillClientsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ClientProxy.AGS_DropdownEntity>> FillClientsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    public interface IClientProxyServiceChannel : ClientProxy.IClientProxyService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    public partial class ClientProxyServiceClient : System.ServiceModel.ClientBase<ClientProxy.IClientProxyService>, ClientProxy.IClientProxyService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ClientProxyServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ClientProxyServiceClient.GetBindingForEndpoint(endpointConfiguration), ClientProxyServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ClientProxyServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ClientProxyServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ClientProxyServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ClientProxyServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ClientProxyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ClientProxy.AGS_Client>> RetrieveAllAsync(string sortBy, string sortOrder, int pageSize, string marker, int currentIndex)
        {
            return base.Channel.RetrieveAllAsync(sortBy, sortOrder, pageSize, marker, currentIndex);
        }
        
        public System.Threading.Tasks.Task<int> PagerCountAsync()
        {
            return base.Channel.PagerCountAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ClientProxy.AGS_Client>> SearchAsync(string key)
        {
            return base.Channel.SearchAsync(key);
        }
        
        public System.Threading.Tasks.Task<ClientProxy.AGS_Client> RetrieveAsync(string id)
        {
            return base.Channel.RetrieveAsync(id);
        }
        
        public System.Threading.Tasks.Task<string> CreateAsync(ClientProxy.AGS_Client user)
        {
            return base.Channel.CreateAsync(user);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAsync(string id, ClientProxy.AGS_Client model)
        {
            return base.Channel.UpdateAsync(id, model);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(string id)
        {
            return base.Channel.DeleteAsync(id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ClientProxy.AGS_DropdownEntity>> FillClientsAsync()
        {
            return base.Channel.FillClientsAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ClientServiceSOAPEndPoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ClientServiceSOAPHttpsEndPoint))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ClientServiceSOAPEndPoint))
            {
                return new System.ServiceModel.EndpointAddress("http://ps-win-cscrmqty.voltasworld.com/GateKeeper/Proxy/ClientProxyService.svc/SO" +
                        "AP");
            }
            if ((endpointConfiguration == EndpointConfiguration.ClientServiceSOAPHttpsEndPoint))
            {
                return new System.ServiceModel.EndpointAddress("https://vserveq.voltasworld.com/GateKeeper/Proxy/ClientProxyService.svc/SOAP");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ClientServiceSOAPEndPoint,
            
            ClientServiceSOAPHttpsEndPoint,
        }
    }
}
