//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrderProxy
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AGS_PurchaseOrder", Namespace="http://schemas.datacontract.org/2004/07/SmartServe.BusinessLogicLayer.BusinessEnt" +
        "ities")]
    public partial class AGS_PurchaseOrder : object
    {
        
        private string AccountIDField;
        
        private string AccountNameField;
        
        private string BranchIDField;
        
        private string BranchNameField;
        
        private string CRMOrderNoField;
        
        private string ConditionTypeField;
        
        private string CreatedByField;
        
        private System.Nullable<System.DateTime> CreatedOnField;
        
        private string DecriptionField;
        
        private string DistChannelField;
        
        private string DivisionField;
        
        private string DivisionIDField;
        
        private string DivisionNameField;
        
        private string DocumentTypeField;
        
        private string IncotermIDField;
        
        private string IncotermNameField;
        
        private string ModifiedByField;
        
        private System.Nullable<System.DateTime> ModifiedOnField;
        
        private string ObjectTypeField;
        
        private string OrderReasonIDField;
        
        private string OrderReasonNameField;
        
        private string OrderTypeField;
        
        private System.Nullable<System.DateTime> PODateField;
        
        private string PONOField;
        
        private string PurchaseOrderIDField;
        
        private System.Collections.Generic.List<PurchaseOrderProxy.AGS_PurchaseOrderItem> PurchaseOrderItemsField;
        
        private string RemarksField;
        
        private string SAPOrderIDField;
        
        private string SalesOrgField;
        
        private string ShiptoPartyIDField;
        
        private string ShiptoPartyNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountID
        {
            get
            {
                return this.AccountIDField;
            }
            set
            {
                this.AccountIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountName
        {
            get
            {
                return this.AccountNameField;
            }
            set
            {
                this.AccountNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BranchID
        {
            get
            {
                return this.BranchIDField;
            }
            set
            {
                this.BranchIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BranchName
        {
            get
            {
                return this.BranchNameField;
            }
            set
            {
                this.BranchNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CRMOrderNo
        {
            get
            {
                return this.CRMOrderNoField;
            }
            set
            {
                this.CRMOrderNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConditionType
        {
            get
            {
                return this.ConditionTypeField;
            }
            set
            {
                this.ConditionTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this.CreatedByField;
            }
            set
            {
                this.CreatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedOn
        {
            get
            {
                return this.CreatedOnField;
            }
            set
            {
                this.CreatedOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Decription
        {
            get
            {
                return this.DecriptionField;
            }
            set
            {
                this.DecriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DistChannel
        {
            get
            {
                return this.DistChannelField;
            }
            set
            {
                this.DistChannelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Division
        {
            get
            {
                return this.DivisionField;
            }
            set
            {
                this.DivisionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DivisionID
        {
            get
            {
                return this.DivisionIDField;
            }
            set
            {
                this.DivisionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DivisionName
        {
            get
            {
                return this.DivisionNameField;
            }
            set
            {
                this.DivisionNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentType
        {
            get
            {
                return this.DocumentTypeField;
            }
            set
            {
                this.DocumentTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IncotermID
        {
            get
            {
                return this.IncotermIDField;
            }
            set
            {
                this.IncotermIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IncotermName
        {
            get
            {
                return this.IncotermNameField;
            }
            set
            {
                this.IncotermNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy
        {
            get
            {
                return this.ModifiedByField;
            }
            set
            {
                this.ModifiedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ModifiedOn
        {
            get
            {
                return this.ModifiedOnField;
            }
            set
            {
                this.ModifiedOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObjectType
        {
            get
            {
                return this.ObjectTypeField;
            }
            set
            {
                this.ObjectTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderReasonID
        {
            get
            {
                return this.OrderReasonIDField;
            }
            set
            {
                this.OrderReasonIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderReasonName
        {
            get
            {
                return this.OrderReasonNameField;
            }
            set
            {
                this.OrderReasonNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderType
        {
            get
            {
                return this.OrderTypeField;
            }
            set
            {
                this.OrderTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PODate
        {
            get
            {
                return this.PODateField;
            }
            set
            {
                this.PODateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PONO
        {
            get
            {
                return this.PONOField;
            }
            set
            {
                this.PONOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PurchaseOrderID
        {
            get
            {
                return this.PurchaseOrderIDField;
            }
            set
            {
                this.PurchaseOrderIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<PurchaseOrderProxy.AGS_PurchaseOrderItem> PurchaseOrderItems
        {
            get
            {
                return this.PurchaseOrderItemsField;
            }
            set
            {
                this.PurchaseOrderItemsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remarks
        {
            get
            {
                return this.RemarksField;
            }
            set
            {
                this.RemarksField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SAPOrderID
        {
            get
            {
                return this.SAPOrderIDField;
            }
            set
            {
                this.SAPOrderIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SalesOrg
        {
            get
            {
                return this.SalesOrgField;
            }
            set
            {
                this.SalesOrgField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShiptoPartyID
        {
            get
            {
                return this.ShiptoPartyIDField;
            }
            set
            {
                this.ShiptoPartyIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShiptoPartyName
        {
            get
            {
                return this.ShiptoPartyNameField;
            }
            set
            {
                this.ShiptoPartyNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AGS_PurchaseOrderItem", Namespace="http://schemas.datacontract.org/2004/07/SmartServe.BusinessLogicLayer.BusinessEnt" +
        "ities")]
    public partial class AGS_PurchaseOrderItem : object
    {
        
        private string ConditionTypeField;
        
        private string CreatedByField;
        
        private System.Nullable<System.DateTime> CreatedOnField;
        
        private string DescriptionField;
        
        private PurchaseOrderProxy.EntityState EntityStateField;
        
        private string Filler1Field;
        
        private string Filler2Field;
        
        private string ItemCodeField;
        
        private string ModifiedByField;
        
        private System.Nullable<System.DateTime> ModifiedOnField;
        
        private string PlantIDField;
        
        private string PlantNameField;
        
        private string ProductIDField;
        
        private string ProductNameField;
        
        private PurchaseOrderProxy.AGS_PurchaseOrder PurchaseOrderField;
        
        private string PurchaseOrderIDField;
        
        private System.Nullable<double> QuantityField;
        
        private System.Nullable<double> TotalValueField;
        
        private string UOMField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConditionType
        {
            get
            {
                return this.ConditionTypeField;
            }
            set
            {
                this.ConditionTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this.CreatedByField;
            }
            set
            {
                this.CreatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedOn
        {
            get
            {
                return this.CreatedOnField;
            }
            set
            {
                this.CreatedOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PurchaseOrderProxy.EntityState EntityState
        {
            get
            {
                return this.EntityStateField;
            }
            set
            {
                this.EntityStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filler1
        {
            get
            {
                return this.Filler1Field;
            }
            set
            {
                this.Filler1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filler2
        {
            get
            {
                return this.Filler2Field;
            }
            set
            {
                this.Filler2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemCode
        {
            get
            {
                return this.ItemCodeField;
            }
            set
            {
                this.ItemCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy
        {
            get
            {
                return this.ModifiedByField;
            }
            set
            {
                this.ModifiedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ModifiedOn
        {
            get
            {
                return this.ModifiedOnField;
            }
            set
            {
                this.ModifiedOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlantID
        {
            get
            {
                return this.PlantIDField;
            }
            set
            {
                this.PlantIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlantName
        {
            get
            {
                return this.PlantNameField;
            }
            set
            {
                this.PlantNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductID
        {
            get
            {
                return this.ProductIDField;
            }
            set
            {
                this.ProductIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName
        {
            get
            {
                return this.ProductNameField;
            }
            set
            {
                this.ProductNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PurchaseOrderProxy.AGS_PurchaseOrder PurchaseOrder
        {
            get
            {
                return this.PurchaseOrderField;
            }
            set
            {
                this.PurchaseOrderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PurchaseOrderID
        {
            get
            {
                return this.PurchaseOrderIDField;
            }
            set
            {
                this.PurchaseOrderIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Quantity
        {
            get
            {
                return this.QuantityField;
            }
            set
            {
                this.QuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> TotalValue
        {
            get
            {
                return this.TotalValueField;
            }
            set
            {
                this.TotalValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UOM
        {
            get
            {
                return this.UOMField;
            }
            set
            {
                this.UOMField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityState", Namespace="http://schemas.datacontract.org/2004/07/SmartServe.BusinessLogicLayer")]
    public enum EntityState : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unchanged = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Added = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Modified = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deleted = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PurchaseOrderProxy.IPurchaseOrderProxyService")]
    public interface IPurchaseOrderProxyService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseOrderProxyService/RetrieveAll", ReplyAction="http://tempuri.org/IPurchaseOrderProxyService/RetrieveAllResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<PurchaseOrderProxy.AGS_PurchaseOrder>> RetrieveAllAsync(string sortBy, string sortOrder, int pageSize, string marker, int currentIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseOrderProxyService/PagerCount", ReplyAction="http://tempuri.org/IPurchaseOrderProxyService/PagerCountResponse")]
        System.Threading.Tasks.Task<int> PagerCountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseOrderProxyService/Search", ReplyAction="http://tempuri.org/IPurchaseOrderProxyService/SearchResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<PurchaseOrderProxy.AGS_PurchaseOrder>> SearchAsync(string Key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseOrderProxyService/Retrieve", ReplyAction="http://tempuri.org/IPurchaseOrderProxyService/RetrieveResponse")]
        System.Threading.Tasks.Task<PurchaseOrderProxy.AGS_PurchaseOrder> RetrieveAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseOrderProxyService/Create", ReplyAction="http://tempuri.org/IPurchaseOrderProxyService/CreateResponse")]
        System.Threading.Tasks.Task<string> CreateAsync(PurchaseOrderProxy.AGS_PurchaseOrder model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseOrderProxyService/Update", ReplyAction="http://tempuri.org/IPurchaseOrderProxyService/UpdateResponse")]
        System.Threading.Tasks.Task<bool> UpdateAsync(string id, PurchaseOrderProxy.AGS_PurchaseOrder model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseOrderProxyService/Delete", ReplyAction="http://tempuri.org/IPurchaseOrderProxyService/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    public interface IPurchaseOrderProxyServiceChannel : PurchaseOrderProxy.IPurchaseOrderProxyService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    public partial class PurchaseOrderProxyServiceClient : System.ServiceModel.ClientBase<PurchaseOrderProxy.IPurchaseOrderProxyService>, PurchaseOrderProxy.IPurchaseOrderProxyService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PurchaseOrderProxyServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(PurchaseOrderProxyServiceClient.GetBindingForEndpoint(endpointConfiguration), PurchaseOrderProxyServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PurchaseOrderProxyServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PurchaseOrderProxyServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PurchaseOrderProxyServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PurchaseOrderProxyServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PurchaseOrderProxyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<PurchaseOrderProxy.AGS_PurchaseOrder>> RetrieveAllAsync(string sortBy, string sortOrder, int pageSize, string marker, int currentIndex)
        {
            return base.Channel.RetrieveAllAsync(sortBy, sortOrder, pageSize, marker, currentIndex);
        }
        
        public System.Threading.Tasks.Task<int> PagerCountAsync()
        {
            return base.Channel.PagerCountAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<PurchaseOrderProxy.AGS_PurchaseOrder>> SearchAsync(string Key)
        {
            return base.Channel.SearchAsync(Key);
        }
        
        public System.Threading.Tasks.Task<PurchaseOrderProxy.AGS_PurchaseOrder> RetrieveAsync(string id)
        {
            return base.Channel.RetrieveAsync(id);
        }
        
        public System.Threading.Tasks.Task<string> CreateAsync(PurchaseOrderProxy.AGS_PurchaseOrder model)
        {
            return base.Channel.CreateAsync(model);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAsync(string id, PurchaseOrderProxy.AGS_PurchaseOrder model)
        {
            return base.Channel.UpdateAsync(id, model);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(string id)
        {
            return base.Channel.DeleteAsync(id);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PurchaseOrderProxySOAPEndPoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.PurchaseOrderProxySOAPHttpsEndPoint))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PurchaseOrderProxySOAPEndPoint))
            {
                return new System.ServiceModel.EndpointAddress("http://ps-win-cscrmqty.voltasworld.com/GateKeeper/Proxy/PurchaseOrderProxyService" +
                        ".svc/SOAP");
            }
            if ((endpointConfiguration == EndpointConfiguration.PurchaseOrderProxySOAPHttpsEndPoint))
            {
                return new System.ServiceModel.EndpointAddress("https://vserveq.voltasworld.com/GateKeeper/Proxy/PurchaseOrderProxyService.svc/SO" +
                        "AP");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            PurchaseOrderProxySOAPEndPoint,
            
            PurchaseOrderProxySOAPHttpsEndPoint,
        }
    }
}
