//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesAreaProxy
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AGS_SalesArea", Namespace="http://schemas.datacontract.org/2004/07/SmartServe.BusinessLogicLayer.BusinessEnt" +
        "ities")]
    public partial class AGS_SalesArea : object
    {
        
        private string CreatedByField;
        
        private System.Nullable<System.DateTime> CreatedOnField;
        
        private string DistChannelField;
        
        private string DistChannelNameField;
        
        private string DivisionField;
        
        private string DivisionNameField;
        
        private string ModifiedByField;
        
        private System.Nullable<System.DateTime> ModifiedOnField;
        
        private string SalesOrgField;
        
        private string SalesOrgNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this.CreatedByField;
            }
            set
            {
                this.CreatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedOn
        {
            get
            {
                return this.CreatedOnField;
            }
            set
            {
                this.CreatedOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DistChannel
        {
            get
            {
                return this.DistChannelField;
            }
            set
            {
                this.DistChannelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DistChannelName
        {
            get
            {
                return this.DistChannelNameField;
            }
            set
            {
                this.DistChannelNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Division
        {
            get
            {
                return this.DivisionField;
            }
            set
            {
                this.DivisionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DivisionName
        {
            get
            {
                return this.DivisionNameField;
            }
            set
            {
                this.DivisionNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy
        {
            get
            {
                return this.ModifiedByField;
            }
            set
            {
                this.ModifiedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ModifiedOn
        {
            get
            {
                return this.ModifiedOnField;
            }
            set
            {
                this.ModifiedOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SalesOrg
        {
            get
            {
                return this.SalesOrgField;
            }
            set
            {
                this.SalesOrgField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SalesOrgName
        {
            get
            {
                return this.SalesOrgNameField;
            }
            set
            {
                this.SalesOrgNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AGS_DropdownEntity", Namespace="http://schemas.datacontract.org/2004/07/SmartServe.BusinessLogicLayer.BusinessEnt" +
        "ities")]
    public partial class AGS_DropdownEntity : object
    {
        
        private string TextField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text
        {
            get
            {
                return this.TextField;
            }
            set
            {
                this.TextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SalesAreaProxy.ISalesAreaProxyService")]
    public interface ISalesAreaProxyService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesAreaProxyService/RetrieveAll", ReplyAction="http://tempuri.org/ISalesAreaProxyService/RetrieveAllResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SalesAreaProxy.AGS_SalesArea>> RetrieveAllAsync(string sortBy, string sortOrder, int pageSize, string marker, int currentIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesAreaProxyService/Count", ReplyAction="http://tempuri.org/ISalesAreaProxyService/CountResponse")]
        System.Threading.Tasks.Task<int> CountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesAreaProxyService/Search", ReplyAction="http://tempuri.org/ISalesAreaProxyService/SearchResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SalesAreaProxy.AGS_SalesArea>> SearchAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesAreaProxyService/Retrieve", ReplyAction="http://tempuri.org/ISalesAreaProxyService/RetrieveResponse")]
        System.Threading.Tasks.Task<SalesAreaProxy.AGS_SalesArea> RetrieveAsync(string salesOrg, string distChannel, string division);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesAreaProxyService/Create", ReplyAction="http://tempuri.org/ISalesAreaProxyService/CreateResponse")]
        System.Threading.Tasks.Task<string> CreateAsync(SalesAreaProxy.AGS_SalesArea model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesAreaProxyService/Delete", ReplyAction="http://tempuri.org/ISalesAreaProxyService/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(string salesOrg, string distChannel, string division);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesAreaProxyService/FillSalesOrgs", ReplyAction="http://tempuri.org/ISalesAreaProxyService/FillSalesOrgsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SalesAreaProxy.AGS_DropdownEntity>> FillSalesOrgsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesAreaProxyService/FillDistChannels", ReplyAction="http://tempuri.org/ISalesAreaProxyService/FillDistChannelsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SalesAreaProxy.AGS_DropdownEntity>> FillDistChannelsAsync(string salesOrg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesAreaProxyService/FillDivisions", ReplyAction="http://tempuri.org/ISalesAreaProxyService/FillDivisionsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SalesAreaProxy.AGS_DropdownEntity>> FillDivisionsAsync(string salesOrg, string distChannel);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    public interface ISalesAreaProxyServiceChannel : SalesAreaProxy.ISalesAreaProxyService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    public partial class SalesAreaProxyServiceClient : System.ServiceModel.ClientBase<SalesAreaProxy.ISalesAreaProxyService>, SalesAreaProxy.ISalesAreaProxyService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SalesAreaProxyServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(SalesAreaProxyServiceClient.GetBindingForEndpoint(endpointConfiguration), SalesAreaProxyServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SalesAreaProxyServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SalesAreaProxyServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SalesAreaProxyServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SalesAreaProxyServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SalesAreaProxyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SalesAreaProxy.AGS_SalesArea>> RetrieveAllAsync(string sortBy, string sortOrder, int pageSize, string marker, int currentIndex)
        {
            return base.Channel.RetrieveAllAsync(sortBy, sortOrder, pageSize, marker, currentIndex);
        }
        
        public System.Threading.Tasks.Task<int> CountAsync()
        {
            return base.Channel.CountAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SalesAreaProxy.AGS_SalesArea>> SearchAsync(string value)
        {
            return base.Channel.SearchAsync(value);
        }
        
        public System.Threading.Tasks.Task<SalesAreaProxy.AGS_SalesArea> RetrieveAsync(string salesOrg, string distChannel, string division)
        {
            return base.Channel.RetrieveAsync(salesOrg, distChannel, division);
        }
        
        public System.Threading.Tasks.Task<string> CreateAsync(SalesAreaProxy.AGS_SalesArea model)
        {
            return base.Channel.CreateAsync(model);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(string salesOrg, string distChannel, string division)
        {
            return base.Channel.DeleteAsync(salesOrg, distChannel, division);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SalesAreaProxy.AGS_DropdownEntity>> FillSalesOrgsAsync()
        {
            return base.Channel.FillSalesOrgsAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SalesAreaProxy.AGS_DropdownEntity>> FillDistChannelsAsync(string salesOrg)
        {
            return base.Channel.FillDistChannelsAsync(salesOrg);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SalesAreaProxy.AGS_DropdownEntity>> FillDivisionsAsync(string salesOrg, string distChannel)
        {
            return base.Channel.FillDivisionsAsync(salesOrg, distChannel);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SalesAreaProxySOAPEndPoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.SalesAreaProxySOAPHttpsEndPoint))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SalesAreaProxySOAPEndPoint))
            {
                return new System.ServiceModel.EndpointAddress("http://ps-win-cscrmqty.voltasworld.com/GateKeeper/Proxy/SalesAreaProxyService.svc" +
                        "/SOAP");
            }
            if ((endpointConfiguration == EndpointConfiguration.SalesAreaProxySOAPHttpsEndPoint))
            {
                return new System.ServiceModel.EndpointAddress("https://vserveq.voltasworld.com/GateKeeper/Proxy/SalesAreaProxyService.svc/SOAP");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            SalesAreaProxySOAPEndPoint,
            
            SalesAreaProxySOAPHttpsEndPoint,
        }
    }
}
