//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProxy
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AGS_User", Namespace="http://schemas.datacontract.org/2004/07/SmartServe.BusinessLogicLayer.BusinessEnt" +
        "ities")]
    public partial class AGS_User : object
    {
        
        private string AddressField;
        
        private string CreatedByField;
        
        private System.Nullable<System.DateTime> CreatedOnField;
        
        private string DeviceIDField;
        
        private string EmailIDField;
        
        private string EmailValidationFlagField;
        
        private UserProxy.EntityState EntityStateField;
        
        private string FirstnameField;
        
        private string GenderField;
        
        private string ImageField;
        
        private string LastNameField;
        
        private string LogonNameField;
        
        private string MobileNumberField;
        
        private string ModifiedByField;
        
        private System.Nullable<System.DateTime> ModifiedOnField;
        
        private string ObjectTypeField;
        
        private string PasswordField;
        
        private System.Nullable<System.DateTime> PasswordExpiryDateField;
        
        private System.Nullable<int> PincodeField;
        
        private string ReportingUserIDField;
        
        private string StatusField;
        
        private string UserIDField;
        
        private string UserTypeField;
        
        private System.Nullable<System.DateTime> ValidFromField;
        
        private System.Nullable<System.DateTime> ValidToField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this.CreatedByField;
            }
            set
            {
                this.CreatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedOn
        {
            get
            {
                return this.CreatedOnField;
            }
            set
            {
                this.CreatedOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceID
        {
            get
            {
                return this.DeviceIDField;
            }
            set
            {
                this.DeviceIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailID
        {
            get
            {
                return this.EmailIDField;
            }
            set
            {
                this.EmailIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailValidationFlag
        {
            get
            {
                return this.EmailValidationFlagField;
            }
            set
            {
                this.EmailValidationFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserProxy.EntityState EntityState
        {
            get
            {
                return this.EntityStateField;
            }
            set
            {
                this.EntityStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Firstname
        {
            get
            {
                return this.FirstnameField;
            }
            set
            {
                this.FirstnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender
        {
            get
            {
                return this.GenderField;
            }
            set
            {
                this.GenderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image
        {
            get
            {
                return this.ImageField;
            }
            set
            {
                this.ImageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogonName
        {
            get
            {
                return this.LogonNameField;
            }
            set
            {
                this.LogonNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileNumber
        {
            get
            {
                return this.MobileNumberField;
            }
            set
            {
                this.MobileNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy
        {
            get
            {
                return this.ModifiedByField;
            }
            set
            {
                this.ModifiedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ModifiedOn
        {
            get
            {
                return this.ModifiedOnField;
            }
            set
            {
                this.ModifiedOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObjectType
        {
            get
            {
                return this.ObjectTypeField;
            }
            set
            {
                this.ObjectTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PasswordExpiryDate
        {
            get
            {
                return this.PasswordExpiryDateField;
            }
            set
            {
                this.PasswordExpiryDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Pincode
        {
            get
            {
                return this.PincodeField;
            }
            set
            {
                this.PincodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReportingUserID
        {
            get
            {
                return this.ReportingUserIDField;
            }
            set
            {
                this.ReportingUserIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserType
        {
            get
            {
                return this.UserTypeField;
            }
            set
            {
                this.UserTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ValidFrom
        {
            get
            {
                return this.ValidFromField;
            }
            set
            {
                this.ValidFromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ValidTo
        {
            get
            {
                return this.ValidToField;
            }
            set
            {
                this.ValidToField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityState", Namespace="http://schemas.datacontract.org/2004/07/SmartServe.BusinessLogicLayer")]
    public enum EntityState : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unchanged = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Added = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Modified = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deleted = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AGS_UserRole", Namespace="http://schemas.datacontract.org/2004/07/SmartServe.BusinessLogicLayer.BusinessEnt" +
        "ities")]
    public partial class AGS_UserRole : object
    {
        
        private System.Nullable<System.DateTime> CreatedOnField;
        
        private UserProxy.EntityState EntityStateField;
        
        private System.Nullable<System.DateTime> ModifiedOnField;
        
        private string RoleIDField;
        
        private string UserIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedOn
        {
            get
            {
                return this.CreatedOnField;
            }
            set
            {
                this.CreatedOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserProxy.EntityState EntityState
        {
            get
            {
                return this.EntityStateField;
            }
            set
            {
                this.EntityStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ModifiedOn
        {
            get
            {
                return this.ModifiedOnField;
            }
            set
            {
                this.ModifiedOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleID
        {
            get
            {
                return this.RoleIDField;
            }
            set
            {
                this.RoleIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AGS_Role", Namespace="http://schemas.datacontract.org/2004/07/SmartServe.BusinessLogicLayer.BusinessEnt" +
        "ities")]
    public partial class AGS_Role : object
    {
        
        private string CreatedByField;
        
        private System.Nullable<System.DateTime> CreatedOnField;
        
        private UserProxy.EntityState EntityStateField;
        
        private string ModifiedByField;
        
        private System.Nullable<System.DateTime> ModifiedOnField;
        
        private string ObjectTypeField;
        
        private string ParentRoleIDField;
        
        private string RoleDescriptionField;
        
        private string RoleIDField;
        
        private string RoleNameField;
        
        private System.Nullable<int> TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this.CreatedByField;
            }
            set
            {
                this.CreatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedOn
        {
            get
            {
                return this.CreatedOnField;
            }
            set
            {
                this.CreatedOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserProxy.EntityState EntityState
        {
            get
            {
                return this.EntityStateField;
            }
            set
            {
                this.EntityStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy
        {
            get
            {
                return this.ModifiedByField;
            }
            set
            {
                this.ModifiedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ModifiedOn
        {
            get
            {
                return this.ModifiedOnField;
            }
            set
            {
                this.ModifiedOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObjectType
        {
            get
            {
                return this.ObjectTypeField;
            }
            set
            {
                this.ObjectTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParentRoleID
        {
            get
            {
                return this.ParentRoleIDField;
            }
            set
            {
                this.ParentRoleIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleDescription
        {
            get
            {
                return this.RoleDescriptionField;
            }
            set
            {
                this.RoleDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleID
        {
            get
            {
                return this.RoleIDField;
            }
            set
            {
                this.RoleIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleName
        {
            get
            {
                return this.RoleNameField;
            }
            set
            {
                this.RoleNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AGS_UserHierarchy", Namespace="http://schemas.datacontract.org/2004/07/SmartServe.BusinessLogicLayer.BusinessEnt" +
        "ities")]
    public partial class AGS_UserHierarchy : object
    {
        
        private string ClientIDField;
        
        private string ClientNameField;
        
        private string CreatedByField;
        
        private System.Nullable<System.DateTime> CreatedOnField;
        
        private UserProxy.EntityState EntityStateField;
        
        private string LobIDField;
        
        private string LobNameField;
        
        private string LogonNameField;
        
        private string ModifiedByField;
        
        private System.Nullable<System.DateTime> ModifiedOnField;
        
        private string OrgIDField;
        
        private string OrgNameField;
        
        private string RoleIDField;
        
        private string RoleNameField;
        
        private string StatusField;
        
        private string UserIDField;
        
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientID
        {
            get
            {
                return this.ClientIDField;
            }
            set
            {
                this.ClientIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientName
        {
            get
            {
                return this.ClientNameField;
            }
            set
            {
                this.ClientNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this.CreatedByField;
            }
            set
            {
                this.CreatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedOn
        {
            get
            {
                return this.CreatedOnField;
            }
            set
            {
                this.CreatedOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserProxy.EntityState EntityState
        {
            get
            {
                return this.EntityStateField;
            }
            set
            {
                this.EntityStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LobID
        {
            get
            {
                return this.LobIDField;
            }
            set
            {
                this.LobIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LobName
        {
            get
            {
                return this.LobNameField;
            }
            set
            {
                this.LobNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogonName
        {
            get
            {
                return this.LogonNameField;
            }
            set
            {
                this.LogonNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy
        {
            get
            {
                return this.ModifiedByField;
            }
            set
            {
                this.ModifiedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ModifiedOn
        {
            get
            {
                return this.ModifiedOnField;
            }
            set
            {
                this.ModifiedOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrgID
        {
            get
            {
                return this.OrgIDField;
            }
            set
            {
                this.OrgIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrgName
        {
            get
            {
                return this.OrgNameField;
            }
            set
            {
                this.OrgNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleID
        {
            get
            {
                return this.RoleIDField;
            }
            set
            {
                this.RoleIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleName
        {
            get
            {
                return this.RoleNameField;
            }
            set
            {
                this.RoleNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AGS_UserReporting", Namespace="http://schemas.datacontract.org/2004/07/SmartServe.BusinessLogicLayer.BusinessEnt" +
        "ities")]
    public partial class AGS_UserReporting : object
    {
        
        private UserProxy.EntityState EntityStateField;
        
        private string ReportingEmailIDField;
        
        private string ReportingIDField;
        
        private string ReportingLogonNameField;
        
        private string ReportingMobileNumberField;
        
        private string ReportingNameField;
        
        private string UserIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserProxy.EntityState EntityState
        {
            get
            {
                return this.EntityStateField;
            }
            set
            {
                this.EntityStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReportingEmailID
        {
            get
            {
                return this.ReportingEmailIDField;
            }
            set
            {
                this.ReportingEmailIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReportingID
        {
            get
            {
                return this.ReportingIDField;
            }
            set
            {
                this.ReportingIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReportingLogonName
        {
            get
            {
                return this.ReportingLogonNameField;
            }
            set
            {
                this.ReportingLogonNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReportingMobileNumber
        {
            get
            {
                return this.ReportingMobileNumberField;
            }
            set
            {
                this.ReportingMobileNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReportingName
        {
            get
            {
                return this.ReportingNameField;
            }
            set
            {
                this.ReportingNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AGS_DropdownEntity", Namespace="http://schemas.datacontract.org/2004/07/SmartServe.BusinessLogicLayer.BusinessEnt" +
        "ities")]
    public partial class AGS_DropdownEntity : object
    {
        
        private string TextField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text
        {
            get
            {
                return this.TextField;
            }
            set
            {
                this.TextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDetailReport", Namespace="http://schemas.datacontract.org/2004/07/SmartServe.BusinessLogicLayer.BusinessEnt" +
        "ities")]
    public partial class UserDetailReport : object
    {
        
        private string EmailIDField;
        
        private string LogonNameField;
        
        private string MobileNumberField;
        
        private System.Collections.Generic.List<UserProxy.AGS_UserHierarchy> PositionsField;
        
        private System.Collections.Generic.List<UserProxy.AGS_UserReporting> ReportingsField;
        
        private string StatusField;
        
        private string UserIdField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailID
        {
            get
            {
                return this.EmailIDField;
            }
            set
            {
                this.EmailIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogonName
        {
            get
            {
                return this.LogonNameField;
            }
            set
            {
                this.LogonNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileNumber
        {
            get
            {
                return this.MobileNumberField;
            }
            set
            {
                this.MobileNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<UserProxy.AGS_UserHierarchy> Positions
        {
            get
            {
                return this.PositionsField;
            }
            set
            {
                this.PositionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<UserProxy.AGS_UserReporting> Reportings
        {
            get
            {
                return this.ReportingsField;
            }
            set
            {
                this.ReportingsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserProxy.IUserProxyService")]
    public interface IUserProxyService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProxyService/RetrieveAll", ReplyAction="http://tempuri.org/IUserProxyService/RetrieveAllResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<UserProxy.AGS_User>> RetrieveAllAsync(string sortBy, string sortOrder, int pageSize, string marker, int currentIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProxyService/PagerCount", ReplyAction="http://tempuri.org/IUserProxyService/PagerCountResponse")]
        System.Threading.Tasks.Task<int> PagerCountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProxyService/Search", ReplyAction="http://tempuri.org/IUserProxyService/SearchResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<UserProxy.AGS_User>> SearchAsync(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProxyService/IsLogonNameAvailable", ReplyAction="http://tempuri.org/IUserProxyService/IsLogonNameAvailableResponse")]
        System.Threading.Tasks.Task<bool> IsLogonNameAvailableAsync(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProxyService/Retrieve", ReplyAction="http://tempuri.org/IUserProxyService/RetrieveResponse")]
        System.Threading.Tasks.Task<UserProxy.AGS_User> RetrieveAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProxyService/Create", ReplyAction="http://tempuri.org/IUserProxyService/CreateResponse")]
        System.Threading.Tasks.Task<string> CreateAsync(UserProxy.AGS_User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProxyService/Update", ReplyAction="http://tempuri.org/IUserProxyService/UpdateResponse")]
        System.Threading.Tasks.Task<bool> UpdateAsync(string id, UserProxy.AGS_User model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProxyService/Delete", ReplyAction="http://tempuri.org/IUserProxyService/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProxyService/ModifyUserRole", ReplyAction="http://tempuri.org/IUserProxyService/ModifyUserRoleResponse")]
        System.Threading.Tasks.Task<bool> ModifyUserRoleAsync(UserProxy.AGS_UserRole userRole);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProxyService/UserRoles", ReplyAction="http://tempuri.org/IUserProxyService/UserRolesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<UserProxy.AGS_Role>> UserRolesAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProxyService/UsersByRole", ReplyAction="http://tempuri.org/IUserProxyService/UsersByRoleResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<UserProxy.AGS_User>> UsersByRoleAsync(string roleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProxyService/ModifyUserHierarchy", ReplyAction="http://tempuri.org/IUserProxyService/ModifyUserHierarchyResponse")]
        System.Threading.Tasks.Task<bool> ModifyUserHierarchyAsync(UserProxy.AGS_UserHierarchy userHierarchy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProxyService/UserHierarchies", ReplyAction="http://tempuri.org/IUserProxyService/UserHierarchiesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<UserProxy.AGS_UserHierarchy>> UserHierarchiesAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProxyService/ModifyUserReporting", ReplyAction="http://tempuri.org/IUserProxyService/ModifyUserReportingResponse")]
        System.Threading.Tasks.Task<bool> ModifyUserReportingAsync(UserProxy.AGS_UserReporting model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProxyService/UserReportings", ReplyAction="http://tempuri.org/IUserProxyService/UserReportingsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<UserProxy.AGS_UserReporting>> UserReportingsAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProxyService/FillAssigmentUsers", ReplyAction="http://tempuri.org/IUserProxyService/FillAssigmentUsersResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<UserProxy.AGS_DropdownEntity>> FillAssigmentUsersAsync(string client, string branch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProxyService/FillReportingUsers", ReplyAction="http://tempuri.org/IUserProxyService/FillReportingUsersResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<UserProxy.AGS_DropdownEntity>> FillReportingUsersAsync(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProxyService/RetrieveUserDetailReport", ReplyAction="http://tempuri.org/IUserProxyService/RetrieveUserDetailReportResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<UserProxy.UserDetailReport>> RetrieveUserDetailReportAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    public interface IUserProxyServiceChannel : UserProxy.IUserProxyService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    public partial class UserProxyServiceClient : System.ServiceModel.ClientBase<UserProxy.IUserProxyService>, UserProxy.IUserProxyService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public UserProxyServiceClient() : 
                base(UserProxyServiceClient.GetDefaultBinding(), UserProxyServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.UserServiceSOAPEndPoint.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UserProxyServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(UserProxyServiceClient.GetBindingForEndpoint(endpointConfiguration), UserProxyServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UserProxyServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(UserProxyServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UserProxyServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(UserProxyServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UserProxyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<UserProxy.AGS_User>> RetrieveAllAsync(string sortBy, string sortOrder, int pageSize, string marker, int currentIndex)
        {
            return base.Channel.RetrieveAllAsync(sortBy, sortOrder, pageSize, marker, currentIndex);
        }
        
        public System.Threading.Tasks.Task<int> PagerCountAsync()
        {
            return base.Channel.PagerCountAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<UserProxy.AGS_User>> SearchAsync(string key)
        {
            return base.Channel.SearchAsync(key);
        }
        
        public System.Threading.Tasks.Task<bool> IsLogonNameAvailableAsync(string key)
        {
            return base.Channel.IsLogonNameAvailableAsync(key);
        }
        
        public System.Threading.Tasks.Task<UserProxy.AGS_User> RetrieveAsync(string id)
        {
            return base.Channel.RetrieveAsync(id);
        }
        
        public System.Threading.Tasks.Task<string> CreateAsync(UserProxy.AGS_User user)
        {
            return base.Channel.CreateAsync(user);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAsync(string id, UserProxy.AGS_User model)
        {
            return base.Channel.UpdateAsync(id, model);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(string id)
        {
            return base.Channel.DeleteAsync(id);
        }
        
        public System.Threading.Tasks.Task<bool> ModifyUserRoleAsync(UserProxy.AGS_UserRole userRole)
        {
            return base.Channel.ModifyUserRoleAsync(userRole);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<UserProxy.AGS_Role>> UserRolesAsync(string id)
        {
            return base.Channel.UserRolesAsync(id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<UserProxy.AGS_User>> UsersByRoleAsync(string roleId)
        {
            return base.Channel.UsersByRoleAsync(roleId);
        }
        
        public System.Threading.Tasks.Task<bool> ModifyUserHierarchyAsync(UserProxy.AGS_UserHierarchy userHierarchy)
        {
            return base.Channel.ModifyUserHierarchyAsync(userHierarchy);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<UserProxy.AGS_UserHierarchy>> UserHierarchiesAsync(string id)
        {
            return base.Channel.UserHierarchiesAsync(id);
        }
        
        public System.Threading.Tasks.Task<bool> ModifyUserReportingAsync(UserProxy.AGS_UserReporting model)
        {
            return base.Channel.ModifyUserReportingAsync(model);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<UserProxy.AGS_UserReporting>> UserReportingsAsync(string id)
        {
            return base.Channel.UserReportingsAsync(id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<UserProxy.AGS_DropdownEntity>> FillAssigmentUsersAsync(string client, string branch)
        {
            return base.Channel.FillAssigmentUsersAsync(client, branch);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<UserProxy.AGS_DropdownEntity>> FillReportingUsersAsync(string userId)
        {
            return base.Channel.FillReportingUsersAsync(userId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<UserProxy.UserDetailReport>> RetrieveUserDetailReportAsync()
        {
            return base.Channel.RetrieveUserDetailReportAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.UserServiceSOAPEndPoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.UserServiceSOAPEndPoint))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/GateKeeper/Proxy/UserProxyService.svc/SOAP");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return UserProxyServiceClient.GetBindingForEndpoint(EndpointConfiguration.UserServiceSOAPEndPoint);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return UserProxyServiceClient.GetEndpointAddress(EndpointConfiguration.UserServiceSOAPEndPoint);
        }
        
        public enum EndpointConfiguration
        {
            
            UserServiceSOAPEndPoint,
        }
    }
}
