//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentProxy
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AGS_Equipment", Namespace="http://schemas.datacontract.org/2004/07/SmartServe.BusinessLogicLayer.BusinessEnt" +
        "ities")]
    public partial class AGS_Equipment : object
    {
        
        private System.Nullable<System.DateTime> CreatedOnField;
        
        private string DivisionField;
        
        private string MaterialDescField;
        
        private string MaterialNoField;
        
        private string MaterialTypeField;
        
        private System.Nullable<System.DateTime> ModifiedOnField;
        
        private string SalesOrgField;
        
        private string StatusField;
        
        private string UOMField;
        
        private string distchannelField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedOn
        {
            get
            {
                return this.CreatedOnField;
            }
            set
            {
                this.CreatedOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Division
        {
            get
            {
                return this.DivisionField;
            }
            set
            {
                this.DivisionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaterialDesc
        {
            get
            {
                return this.MaterialDescField;
            }
            set
            {
                this.MaterialDescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaterialNo
        {
            get
            {
                return this.MaterialNoField;
            }
            set
            {
                this.MaterialNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaterialType
        {
            get
            {
                return this.MaterialTypeField;
            }
            set
            {
                this.MaterialTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ModifiedOn
        {
            get
            {
                return this.ModifiedOnField;
            }
            set
            {
                this.ModifiedOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SalesOrg
        {
            get
            {
                return this.SalesOrgField;
            }
            set
            {
                this.SalesOrgField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UOM
        {
            get
            {
                return this.UOMField;
            }
            set
            {
                this.UOMField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string distchannel
        {
            get
            {
                return this.distchannelField;
            }
            set
            {
                this.distchannelField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AGS_DropdownEntity", Namespace="http://schemas.datacontract.org/2004/07/SmartServe.BusinessLogicLayer.BusinessEnt" +
        "ities")]
    public partial class AGS_DropdownEntity : object
    {
        
        private string TextField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text
        {
            get
            {
                return this.TextField;
            }
            set
            {
                this.TextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EquipmentProxy.IEquipmentProxyService")]
    public interface IEquipmentProxyService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquipmentProxyService/RetrieveAll", ReplyAction="http://tempuri.org/IEquipmentProxyService/RetrieveAllResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<EquipmentProxy.AGS_Equipment>> RetrieveAllAsync(string sortBy, string sortOrder, int pageSize, string marker, int currentIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquipmentProxyService/PagerCount", ReplyAction="http://tempuri.org/IEquipmentProxyService/PagerCountResponse")]
        System.Threading.Tasks.Task<int> PagerCountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquipmentProxyService/Search", ReplyAction="http://tempuri.org/IEquipmentProxyService/SearchResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<EquipmentProxy.AGS_Equipment>> SearchAsync(string Key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquipmentProxyService/FillEquipmentPlants", ReplyAction="http://tempuri.org/IEquipmentProxyService/FillEquipmentPlantsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<EquipmentProxy.AGS_DropdownEntity>> FillEquipmentPlantsAsync(string materialNo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    public interface IEquipmentProxyServiceChannel : EquipmentProxy.IEquipmentProxyService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    public partial class EquipmentProxyServiceClient : System.ServiceModel.ClientBase<EquipmentProxy.IEquipmentProxyService>, EquipmentProxy.IEquipmentProxyService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public EquipmentProxyServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(EquipmentProxyServiceClient.GetBindingForEndpoint(endpointConfiguration), EquipmentProxyServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EquipmentProxyServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(EquipmentProxyServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EquipmentProxyServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(EquipmentProxyServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EquipmentProxyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<EquipmentProxy.AGS_Equipment>> RetrieveAllAsync(string sortBy, string sortOrder, int pageSize, string marker, int currentIndex)
        {
            return base.Channel.RetrieveAllAsync(sortBy, sortOrder, pageSize, marker, currentIndex);
        }
        
        public System.Threading.Tasks.Task<int> PagerCountAsync()
        {
            return base.Channel.PagerCountAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<EquipmentProxy.AGS_Equipment>> SearchAsync(string Key)
        {
            return base.Channel.SearchAsync(Key);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<EquipmentProxy.AGS_DropdownEntity>> FillEquipmentPlantsAsync(string materialNo)
        {
            return base.Channel.FillEquipmentPlantsAsync(materialNo);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.EquipmentProxySOAPEndPoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.EquipmentProxySOAPHttpsEndPoint))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.EquipmentProxySOAPEndPoint))
            {
                return new System.ServiceModel.EndpointAddress("http://ps-win-cscrmqty.voltasworld.com/GateKeeper/Proxy/EquipmentProxyService.svc" +
                        "/SOAP");
            }
            if ((endpointConfiguration == EndpointConfiguration.EquipmentProxySOAPHttpsEndPoint))
            {
                return new System.ServiceModel.EndpointAddress("https://vserveq.voltasworld.com/GateKeeper/Proxy/EquipmentProxyService.svc/SOAP");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            EquipmentProxySOAPEndPoint,
            
            EquipmentProxySOAPHttpsEndPoint,
        }
    }
}
